= Install and Start Using the Scala SDK with Couchbase Server
:navtitle: Start Using the SDK
:page-topic-type: howto
:page-aliases: ../../hello-world/pages/start-using-sdk.adoc

[abstract]
The Couchbase Scala SDK enables you to interact with a Couchbase Server cluster from the Scala language.

WARNING: These pages cover the second _Alpha_ of the Couchbase Scala SDK -- 1.0 _alpha_.
As such they are likely to change without notice.
The _alpha_ code _should not_ be used in production.

== Installing the SDK

The Couchbase Scala SDK is available on the Couchbase Maven repository and can be included in your `build.gradle`
like this:

[source,groovy]
----
repositories {
    maven {
        url 'http://files.couchbase.com/maven2'
    }
}

dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.12', version: '1.0.0-alpha.2'
}
----

Or into your Maven pom.xml:

[source,xml]
----
<repositories>
    <repository>
      <id>couchbase</id>
      <name>Couchbase Preview Repository</name>
      <url>http://files.couchbase.com/maven2</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.12</artifactId>
        <version>1.0.0-alpha.2</version>
    </dependency>
</dependencies>
----

Or for SBT:

[source,sbt]
----
resolvers += "Couchbase Snapshots" at "http://files.couchbase.com/maven2"
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.0.0-alpha.2"
----

== Connecting to a Cluster

Now you have the Scala client installed, try out the following to connect to a Couchbase cluster.

First pull in all the imports we'll be using:
[source,scala]
----
include::example$Cluster.scala[tag=imports]
----

Now we can connect to the cluster:

[source,scala]
----
include::example$Cluster.scala[tag=cluster]
----

Of course, you'll need to change the IP address to match your own cluster's.

Couchbase uses xref:6.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources, so specify the username and password of a user you've setup during installation of the Couchbase Data Platform.

Now we can open a Couchbase bucket, and its default collection:

[source,scala]
----
include::example$Cluster.scala[tag=resources]
----

The Scala SDK is forwards-looking to future releases of Couchbase Server which will support the new features of _scopes_ and
_collections_. These will allow documents to be grouped in a more granular way than buckets allow.  For now, we
will just open the 'default collection', which includes all documents in a bucket, and is forwards and backwards compatible
with all supported versions of Couchbase Server.

== JSON
Now we can do some simple Key Value (KV) operations.  First, let's create some JSON.

The Scala SDK directly supports several popular JSON libraries, including https://github.com/lihaoyi/upickle[uPickle/uJson], https://circe.github.io/circe/[Circe], https://github.com/playframework/play-json[Play Json], https://github.com/typelevel/jawn[Jawn], and https://github.com/json4s/json4s[Json4s] (if you'd like to see your favourite supported, please let us know).
In addition you can supply JSON encoded into a `String` or `Array[Byte]`, opening the door to any JSON library; https://jsoniter.com/[Jsoniter] and https://github.com/FasterXML/jackson[Jackson] have been tested this way, but any should work.

You can also directly encode and decode Scala case classes to and from the SDK.

To make things easy and to help get you started, the Scala SDK also bundles a home-grown small JSON library, which you are free to use instead of or alongside any of the other supported JSON libraries.
The philosophy behind this library is to provide a very easy-to-use API and the fastest JSON implementation possible.

Here's how to get started with it:

[source,scala]
----
include::example$Cluster.scala[tag=json]
----

== Key-Value Operations
And now let's upsert it into Couchbase (upsert is an operation that will insert the document if it does not exist, or replace it if it does).  
We need to provide a unique ID for the JSON, and we'll use a UUID here:

[source,scala]
----
include::example$Cluster.scala[tag=upsert]
----

[NOTE]
A note on error handling: the Scala SDK will not throw exceptions. 
Instead, methods that can error will return a Scala `Try` object, which can either be a `Success` containing the result, or a `Failure` containing a _Throwable_ exception. 
The easiest way to handle a single operation is with pattern matching, as shown above.

Now let's get the data back (this example will look a little messy, but we'll see how to clean it up shortly):

[source,scala]
----
include::example$Cluster.scala[tag=get]
----

Here we're fetching the value for the key `docId`, converting that value to a `JsonObjectSafe` (a simple wrapper around `JsonObject` that returns `Try` rather than throwing exceptions), and then accessing the value of the *status* key as a String.

== Better Error Handling
All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using flatMap, like this:

[source,scala]
----
include::example$Cluster.scala[tag=get-map]
----

Alternatively, you can use a for-comprehension, like so:

[source,scala]
----
include::example$Cluster.scala[tag=get-for]
----

== Next Steps
You now know the basics of connecting to a Couchbase cluster, creating some JSON, and performing Key-Value operations.

Key-Value operations are described in detail xref:scala-sdk:howtos:kv-operations.adoc[here].

For performing operations against multiple documents, check out how to use N1QL in Scala xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[here].

API reference are available in a javadocs jar alongside the release.
