= Field Level Encryption from the SDK
:description: The Field Level Encryption library enables encryption and decryption of JSON fields, to support FIPS-140-2 compliance.
:page-edition: Enterprise Edition
// :page-aliases: ROOT:encrypting-using-sdk.adoc

[abstract]
{description}



[TIP]
.Native Encryption at Rest
====
Server 8.x (and new Capella Operational clusters) offer xref:server:learn:security/native-encryption-at-rest-overview.adoc[encryption at rest].
It's a comprehensive way of encrypting all data in a non-ephemeral bucket,
as well as logs, configuration data, and audit data.
However, you may prefer the relative simplicity of key management in Field Level Encryption for use cases where there are a limited number of data to be encrypted.
====



Client-side implementation of Field Level Encryption has not historically been a feature of the Couchbase Scala SDK,
but it is hoped to introduce it eventually.

Field Level Encryption _is_ available in most of the other SDKs,
including the xref:java-sdk:howtos:encrypting-using-sdk.adoc[Java SDK].
