= Search
:description: You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server, and to perform vector searches.
:page-topic-type: howto
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

Full Text Search (FTS) allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase buckets.

It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.
The Scala SDK exposes an API for performing FTS queries which abstracts away the complexity of using the underlying REST API.

From Couchbase Server 7.6, the FTS service also supports powerful vector search.

== Examples

After familiarizing yourself with how to create and query a search index in the UI, you can query it from the SDK.

You'll need to know whether a global or scoped search index has been created - see <<Scoped vs Global Indexes>> for details.
If your Couchbase Server is pre 7.6 it will certainly be a global index, otherwise, the UI will tell you which it is.

These APIs are used for querying global search indexes: `cluster.searchQuery()`, and `cluster.search()`.
And this one is used for scoped search indexes: `scope.search()`.

The `cluster.searchQuery()` API supports FTS queries (`SearchQuery`), while `scope.search()` additionally supports the `VectorSearch` added in 7.6.

Most of this documentation will focus on the former API, as the latter is in @Stability.Uncommitted status.

We will perform an FTS query here - see the <<vector search>> section for examples of that.

The examples below use these imports:

[source.scala]
----
include::example$FTS.scala[tag=imports,indent=0]
----

The `cluster.searchQuery()` API takes the name of the index and the type of query as required arguments, and allows additional options to be provided if needed.

Here is a simple `MatchQuery` that looks for the text “swanky” using a defined index:

[source.scala]
----
include::example$FTS.scala[tag=basic,indent=0]
----

All simple query types are created in the same manner.
Some have additional properties, which can be seen in common query type descriptions.
Couchbase FTS's xref:{version-server}@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the range wanted.

== Working with Results

The result of a search query has three components: rows, facets, and metadata.
Rows are the documents that match the query.
Facets allow the aggregation of information collected on a particular result set.
Metadata holds additional information not directly related to your query, such as total rows and how long the query took to execute in the cluster.

[source.scala]
----
include::example$FTS.scala[tag=results,indent=0]
----



== Scoped vs Global Indexes
The FTS APIs exist on both the `Cluster` and `Scope` objects.

This is because FTS supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` or `Cluster.search()` for global indexes, and `Scope.search()` for scoped indexes.


== Vector Search
As of Couchbase Server 7.6, the FTS service supports vector search in additional to traditional full text search queries.
// todo link to the server docs when available

=== Examples
==== Single vector query
In this first example we are performing a single vector query:

[source.scala]
----
include::example$FTS.scala[tag=vector1,indent=0]
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional FTS query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `float[]`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the FTS index "vector-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.search()`.
If it was a global index we would use `cluster.search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

==== Multiple vector queries
You can run multiple vector queries together:

[source.scala]
----
include::example$FTS.scala[tag=vector2,indent=0]
----

How the results are combined (ANDed or ORed) can be controlled with `VectorSearch.vectorSearchOptions(VectorSearchOptions().vectorQueryCombination(VectorQueryCombination.And))`.

==== Combining FTS and vector queries
You can combine a traditional FTS query with vector queries:

[source.scala]
----
include::example$FTS.scala[tag=vector3,indent=0]
----

==== FTS queries
And note that traditional FTS queries, without vector search, are also supported with the new `cluster.search()` / `scope.search()` APIs:

[source.scala]
----
include::example$FTS.scala[tag=vector4,indent=0]
----

The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the Couchbase Query Service, FTS allows provides optional _Read-Your-Own-Writes (RYOW)_ consistency, ensuring results contain information from updated indexes:

[source.scala]
----
include::example$FTS.scala[tag=consistency,indent=0]
----
