= Search
:description: You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.
:page-pagination: full
:page-toclevels: 2


[abstract]
{description}


// add scoring note on https://docs.couchbase.com/server/current/release-notes/relnotes.html#known-issues-761 



Full Text Search or FTS allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.
The Scala SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying REST API.

== Examples
The examples below use these imports:

[source.scala]
----
include::devguide:example$scala/FTS.scala[tag=imports,indent=0]
----

Search queries are executed at Cluster level (not bucket or collection).
Here is a simple MatchQuery that looks for the text “swanky” using a defined index:

[source.scala]
----
include::devguide:example$scala/FTS.scala[tag=basic,indent=0]
----

All simple query types are created in the same manner.
Some have additional properties, which can be seen in common query type descriptions.
Couchbase FTS's xref:{version-server}@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the range wanted.

[TIP]
.Search Results Limit
====
By default, the Search Service returns only the first 10 matches (`size: 10`, `from: 0`).
To retrieve more results, you must explicitly define pagination settings such as `size` or `from` in your query.

For information about formatting your Search query and specifying limits, see xref:server:search:search-request-params.adoc[].

For information about pagination in Search responses, see xref:server:fts:fts-search-response.adoc#pagination[Pagination].
====


== Working with Results

The result of a search query has three components: rows, facets, and metadata.
Rows are the documents that match the query.
Facets allow the aggregation of information collected on a particular result set.
Metadata holds additional information not directly related to your query, such as total rows and how long the query took to execute in the cluster.

[source.scala]
----
include::devguide:example$scala/FTS.scala[tag=results,indent=0]
----


== Consistency

Like the Couchbase Query Service, FTS allows provides optional _Read-Your-Own-Writes (RYOW)_ consistency, ensuring results contain information from updated indexes:

[source.scala]
----
include::devguide:example$scala/FTS.scala[tag=consistency,indent=0]
----

