= Health Check
:description: pass:q[Health Check provides `ping()` and `diagnostics()` tests for the health of the network and the cluster.]
:page-aliases: concept-docs:health-check.adoc
// :page-aliases: ROOT:health-check.adoc
:page-toclevels: 2



[abstract]
{description}



In today's distributed and virtual environments, users will often not have full administrative control over their whole network.
Working in distributed environments is hard. Latencies come and go, so do connections in their entirety.
Is it a network glitch, or is the remote cluster down?
Sometimes just knowing the likely cause is enough to get a good start on a workaround, or at least avoid hours wasted on an inappropriate solution.

Health Check features _Ping_ to check nodes are still healthy, and to force idle connections to be kept alive in environments with eager shutdowns of unused resources.
_Diagnostics_ requests a report from a node, giving instant health check information.



// Uses
include::{version-common}@sdk:pages:partial$health-check.adoc[tag="uses"]



== Ping

`Ping` _actively_ queries the status of the specified services,giving status and latency information for every node reachable.
In addition to its use as a monitoring tool, a regular `Ping` can be used in an environment which does not respect keep alive values for a connection.





[source,scala]
----
cluster.ping(PingOptions().serviceTypes(Set(ServiceType.KV, ServiceType.QUERY)))
    .map(result => System.out.println(result))
/*
{
    "config_rev":1822,
    "id":"0x102f09dc0",
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "services":{
        "kv":[
            {
                "id":"0x104802900",
                "latency_us":1542,
                "local":"10.112.195.1:51707",
                "remote":"10.112.195.101:11210",
                "scope":"travel-sample",
                "status":"ok"
            },
            {
                "id":"0x1029253d0",
                "latency_us":6639,
                "local":"10.112.195.1:51714",
                "remote":"10.112.195.103:11210",
                "scope":"travel-sample",
                "status":"ok"
            },
            {
                "id":"0x102924bc0",
                "latency_us":1240660,
                "local":"10.112.195.1:51713",
                "remote":"10.112.195.102:11210",
                "scope":"travel-sample",
                "status":"timeout"
            }
        ],
        "n1ql":[
            {
                "id":"0x10291d980",
                "latency_us":3787,
                "local":"10.112.195.1:51710",
                "remote":"10.112.195.101:8093",
                "status":"ok"
            },
            {
                "id":"0x1029240f0",
                "latency_us":9321,
                "local":"10.112.195.1:51712",
                "remote":"10.112.195.103:8093",
                "status":"ok"
            },
            {
                "id":"0x102923350",
                "latency_us":7003363,
                "local":"10.112.195.1:51711",
                "remote":"10.112.195.102:8093",
                "status":"timeout"
            }
        ]
    },
    "version":1
}
*/
----



=== More Information

For further use of `ping()`, refer to https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#ping(options:com.couchbase.client.scala.diagnostics.PingOptions):scala.util.Try%5Bcom.couchbase.client.core.diagnostics.PingResult%5D[the API docs] --
including https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/diagnostics/PingOptions.html[PingOptions].










== Diagnostics


`Diagnostics` returns a list of the nodes that the SDK currently has (or had) a connection to, and the current status of the connection.
However this call _does not_ actively poll the nodes, reporting instead the state the last time it tried to access each node.
If you want the _current_ status, then use xref:#ping[Ping].



[source,scala]
----
cluster.diagnostics()
  .map(result => System.out.println(result))
/*
{
    "id":"0x10290d100","kv":[
        {
            "id":"0000000072b21d66",
            "last_activity_us":2363294,
            "local":"10.112.195.1:51473",
            "remote":"10.112.195.101:11210",
            "status":"connected"
        },
        {
            "id":"000000000ba84e5e",
            "last_activity_us":7369021,
            "local":"10.112.195.1:51486",
            "remote":"10.112.195.102:11210",
            "status":"connected"
        },
        {
            "id":"0000000077689398",
            "last_activity_us":4855640,
            "local":"10.112.195.1:51409",
            "remote":"10.112.195.103:11210",
            "status":"connected"
        }
    ],
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "version":1
}
*/
----


=== More Information


For specifics, refer to the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#diagnostics(options:com.couchbase.client.scala.diagnostics.DiagnosticsOptions):scala.util.Try%5Bcom.couchbase.client.core.diagnostics.DiagnosticsResult%5D[API docs] -- 
including https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/diagnostics/DiagnosticsOptions.html[DiagnosticsOptions].










////
At its simplest, `ping` provides information about the current state of the connections in the Couchbase Cluster, by actively polling:

// 2.7 SDK
[source,java]
----
void printDiagnostics(Bucket bucket) {
    bucket.ping();
    DiagnosticsReport report = cluster.diagnostics();
    System.out.println(report.exportToJson(true));
}
----

Which, for a single-node test cluster, will return a payload similar to this:
// TODO -- multiple nodes

// 2.x SDK
----
{
  "services" : {
    "view" : [ {
      "last_activity_us" : 2863,
      "state" : "connected",
      "id" : "0x46ee8659",
      "remote" : "localhost:8092",
      "local" : "localhost:53309"
    } ],
    "fts" : [ {
      "last_activity_us" : 2625,
      "state" : "connected",
      "id" : "0x1c5de614",
      "remote" : "localhost:8094",
      "local" : "localhost:53308"
    } ],
    "kv" : [ {
      "last_activity_us" : 19243,
      "state" : "connected",
      "id" : "0x7d942ebb",
      "remote" : "localhost:11210",
      "local" : "localhost:53307"
    } ],
    "n1ql" : [ {
      "last_activity_us" : 1963,
      "state" : "connected",
      "id" : "0x8de927d",
      "remote" : "localhost:8093",
      "local" : "localhost:53310"
    } ]
  },
  "sdk" : "couchbase-java-client/2.5.8 (git: 2.5.8, core: 1.5.8) (Mac OS X/10.13.4 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_171-b11)",
  "id" : "9c7e2ac7-9a41-4e67-8cdf-bf16abaa35a4",
  "version" : 1
}
----

If you only wish to know if there's a connection that's up, filter out the rest of the information:

// 2.x example
[source,java]
----
boolean allEndpointsConnected(DiagnosticsReport report) {
    for (EndpointHealth endpoint : report.endpoints()) {
        if (endpoint.state() != LifecycleState.CONNECTED) {
            return false;
        }
    }
    return true;
}
----

////



// Diag
////
[source,javascript]
----
bucket.diagnostics((err, res) => {
    console.log(res)
})
/*
{
    "id":"0x10290d100","kv":[
        {
            "id":"0000000072b21d66",
            "last_activity_us":2363294,
            "local":"10.112.195.1:51473",
            "remote":"10.112.195.101:11210",
            "status":"connected"
        },
        {
            "id":"000000000ba84e5e",
            "last_activity_us":7369021,
            "local":"10.112.195.1:51486",
            "remote":"10.112.195.102:11210",
            "status":"connected"
        },
        {
            "id":"0000000077689398",
            "last_activity_us":4855640,
            "local":"10.112.195.1:51409",
            "remote":"10.112.195.103:11210",
            "status":"connected"
        }
    ],
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "version":1
}
*/
----
////
