= Managing Connections
:description: This section describes how to connect the {name-sdk} to a Couchbase cluster.
// :page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced
:page-toclevels: 2


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting Cloud connections.


Our xref:hello-world:start-using-sdk[Getting Started pages] cover the basics of making a connection to a Capella or self-managed Couchbase cluster.
This page is a wider look at the topic.


== Connecting to a Cluster

The examples below use these imports:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=imports,indent=0]
----

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to buckets, scopes, and collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.connect()` with a <<connection-strings, connection string>>, username, and password:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=initial,indent=0]
----

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=multiple,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.


=== Waiting for Bootstrap Completion

Opening resources is asynchronous.
That is, the call to `cluster.bucket` or `Cluster.connect` will complete instantly, and opening that resource will continue in the background.

You can force waiting for the resource to be opened with a call to `waitUntilReady`, which is available on both the `Cluster` and `Bucket`.
Here is an example of using it on the bucket:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=wait-until-ready,indent=0]
----

If not present, then the first Key Value (KV) operation on the bucket will wait for it to be ready.
Any issues opening that bucket (for instance, if it does not exist), will result in an error being raised from that data operation.

Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster -- 
this is xref:project-docs:compatibility.adoc#network-requirements[not recommended in production deployments], but often occurs during development.
See the <<working-in-the-cloud,Cloud section>> below for some suggestions of settings adjustments.


=== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
127.0.0.1
----

.Connection string with two seed nodes
----
nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
127.0.0.1?io.networkResolution=external&timeout.kvTimeout=10s
----

The full list of recognized parameters is documented in the client settings reference.
Any client setting with a system property name may also be specified as a connection string parameter (without the `com.couchbase.env.` prefix).

WARNING: When creating a `Cluster` using a custom `ClusterEnvironment`, *_connection string parameters are ignored_*, since client settings are frozen when the cluster environment is built.


=== Cluster Environment

A `ClusterEnvironment` manages shared resources like thread pools, timers, and schedulers.
It also holds the client settings.
One way to customize the client's behavior is to build your own `ClusterEnvironment` with custom settings:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=env,indent=0]
----

This is a verbose example for simplicity, and the user may prefer to use `flatMap` or a for-comprehension to combine the multiple `Try`.

Note there are `com.couchbase.client.scala.env` and `com.couchbase.client.core.env` versions of all environment parameters: be sure to import the `.scala` versions.

TIP: If you create a `Cluster` without specifying a custom environment, the client creates a default environment used exclusively by that `Cluster`.
This default `ClusterEnvironment` is managed completely by the Scala SDK, and is automatically shut down when the associated `Cluster` is disconnected.


=== Connection Lifecycle

Most of the high-level classes in the Scala SDK are designed to be safe for concurrent use by multiple threads.
You will get the best performance if you share and reuse instances of `ClusterEnvironment`, `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.

Before your application stops, gracefully shut down the client by calling the `disconnect()` method of each `Cluster` you created.
If you created any `ClusterEnvironment` instances, call their `shutdown()` method after disconnecting the associated clusters.

[#multiple-clusters]
=== Connecting to Multiple Clusters

If a single application needs to connect to multiple Couchbase Server clusters, we recommend creating a single `ClusterEnvironment` and sharing it between the `Clusters`.
We will use a for-comprehension here to avoid excessive `Try` juggling.

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=shared,indent=0]
----

Remember, whenever you manually create a `ClusterEnvironment` like this, the SDK will not shut it down when you call `Cluster.disconnect()`.
Instead you are responsible for shutting it down after disconnecting all clusters that share the environment.


[#ssl]
== Secure Connections

Both Couchbase Capella, and the
xref:{version-server}@server:introduction:editions.adoc#enterprise-edition[Enterprise Edition] of self-managed Couchbase Server,
 support full encryption of client-side traffic using Transport Layer Security (TLS).
That includes data (key-value type) operations, queries, and configuration communication.
Make sure you have the Enterprise Edition of Couchbase Server, or a Couchbase Capella account, before proceeding with configuring encryption on the client side.

[{tabs}]
====
Couchbase Capella::
+
--
The Scala SDK bundles Capella’s standard root certificate by default.
This means you don’t need any additional configuration to enable TLS -- simply use `couchbases://` in your connection string.

NOTE: Capella's root certificate is *not* signed by a well known CA (Certificate Authority).
However, as the certificate is bundled with the SDK, it is trusted by default.
--

Self-Managed Couchbase Server::
+
--
As of SDK 1.4, if you connect to a Couchbase Server cluster with a root certificate issued by a trusted CA (Certificate Authority), you no longer need to configure this in the `securityConfig` settings.

The cluster's root certificate just needs to be issued by a CA whose certificate is in the JVM's trust store.
This includes well known CAs (e.g., GoDaddy, Verisign, etc...), plus any other CA certificates that you wish to add.

TIP: The JVM's trust store is represented by a file named `cacerts`, which can be found inside your Java installation folder.

You can still provide a certificate explicitly if necessary:

. Get the CA certificate from the cluster and save it in a text file.
. Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.

// TODO: not entirely sure this is correct, need to check this.
//Setting `TLSSkipVerify` is a workaround if you need to use `couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as `cluster.cert`).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption and pass it the path to the certificate file.

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=secure,indent=0]
----

Then use this custom `ClusterEnvironment` when opening the connection to the cluster.
See <<cluster-environment>> for an example of creating a `Cluster` with a custom environment.

If you want to verify it's actually working, you can use a tool like [.cmd]`tcpdump`.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}
----

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207 which is the default encrypted port):

----
E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.	...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----
--
====


The SDK includes the certificate for Capella.
// , but you may wish to
// [use your own certificate], 
// or be
If you are working with a self-managed Couchbase cluster,
add the certificate with:

[source,scala]
----
ClusterEnvironment env = ClusterEnvironment.builder()
    .securityConfig(SecurityConfig.enableTls(true).trustCertificate(Paths.get("/path/to/cluster.cert"))).build();
----


== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes, a client running outside that environment may need additional information in order to connect the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertise its external address as well as any custom port mapping.
This is done with the https://docs.couchbase.com/server/6.5/cli/cbcli/couchbase-cli-setting-alternate-address.html[`setting-alternate-address` CLI command] introduced in Couchbase Server 6.5.
A node configured in this way will advertise two addresses: one for connecting from the same network, and another for connecting from an external network.

On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports using the overloaded `Cluster.connect()` method that takes a set of `SeedNode` objects instead of a connection string.

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=seed-nodes,indent=0]
----

TIP: In a deployment that uses multi-dimensional scaling, a custom KV port is only applicable for nodes running the KV service.
A custom manager port may be specified regardless of which services are running on the node.

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.
If the detection heuristic fails in your environment, you can override it by setting the `io.networkResolution` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.

NOTE: Any TLS certificates must be set up at the point where the connections are being made.


// DNS-SRV

include::{version-common}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

DNS SRV bootstrapping is enabled by default in the {name-sdk}.
In order to make the SDK use the SRV records, you need to pass in the hostname from your records (here `example.com`):

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=dnssrv,indent=0]
----

If the DNS SRV records could not be loaded properly you'll get the exception logged and the given host name will be used as a A record lookup.

----
WARNING: DNS SRV lookup failed, proceeding with normal bootstrap.
javax.naming.NameNotFoundException: DNS name not found [response code 3];
   remaining name '_couchbase._tcp.example.com'
	at com.sun.jndi.dns.DnsClient.checkResponseCode(DnsClient.java:651)
	at com.sun.jndi.dns.DnsClient.isMatchResponse(DnsClient.java:569)
----

Also, if you pass in more than one node, DNS SRV bootstrap will not be initiated:

----
INFO: DNS SRV enabled, but less or more than one seed node given.
Proceeding with normal bootstrap.
----


== Cloud Native Gateway


Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.
// Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.

The protocol implements a gRPC-style interface between the SDK and Couchbase Server (in this case, only available in the Server running on Kubernetes or OpenShift, with a forthcoming release of xref:operator::overview.adoc[Couchbase Autonomous Operator].



=== Limitations

The underlying protocol will not work with certain legacy features: MapReduce Views (a deprecated Service -- 
use xref:howtos:sqlpp-queries-with-sdk.adoc[Query] instead) and 
Memcached buckets (superseded by the improved xref:{server_version}@server:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[Ephemeral Buckets]).

The following are not currently implemented over the `couchbase2://` protocol:

* Authentication by client certificate.
* Multi-document ACID transactions.
* Analytics service.
* Health Check.

There are some different behaviors seen with this protocol:

* Some config options are unsupported -- see the xref:ref:client-settings.adoc#cloud-native-gateway[Settings page].
* The SDK will poll the gRPC channels until they are in a good state, or return an error, or timeout while waiting -- in our standard protocol there is an option of setting `waitUntilReady()` for just certain services to become available.
* Some error codes are more generic -- in cases where the client would not be expected to need to take specific action -- but should cause no problem, unless you have written code looking at individual strings within the error messages.
* Although documents continue to be stored compressed by Couchbase Server, they will not be transmitted in compressed form (to and from the client) over the wire, using `couchbase2://`.


== Working in the Cloud

include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=cloud]


== Async and Reactive APIs

The Couchbase Scala SDK provides first-class support for asynchronous and reactive programming.
In fact, the synchronous API is just a thin wrapper around the asynchronous API.

Methods in the asynchronous API return instances of the standard Scala `Future`.

The Scala SDK's reactive API is built on link:https://projectreactor.io[Project Reactor] and the link:https://github.com/reactor/reactor-scala-extensions[Scala extensions].
Reactor implements the standard Reactive Streams API introduced in Scala 9, and extends it with a rich set of useful operators.
Methods in the reactive API return instances of `SFlux` or `SMono`.

If you wish to embrace the async or reactive programming model, there are two ways to get started:

* Call `async` or `reactive` on the object to access its `Async*` or `Reactive*` counterpart.
For example, if you have a `Collection` called `myCollection`, you can obtain a `ReactiveCollection` by calling `myCollection.reactive`.
* Instantiate an `AsyncCluster` or `ReactiveCluster` in the first place.
The `bucket()` method of an `AsyncCluster` returns an `AsyncBucket`, while the `bucket()` method of a `ReactiveCluster` turns a `ReactiveBucket`.

So if you are connecting to the bucket synchronously but then want to switch over to asynchronous data operations, you can do it like this:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=blocking-to-async,indent=0]
----

On the other hand, you can use the Async API right from the beginning:
[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=async,indent=0]
----

Here's the same example, but using the Reactive API instead of the Async API:

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=reactive,indent=0]
----


== Next Steps

* xref:secure-connections.adoc[Certificate Authentication] 
