= N1QL Queries from the SDK
:navtitle: N1QL from the SDK
:page-topic-type: howto
:page-aliases: n1ql-query
:lang: Scala
:version: 1.0.0 alpha.6
:example-source: 1.0@scala-sdk:howtos:example$Queries.scala
:example-source-lang: scala

include::1.0@scala-sdk:howtos:partial$n1ql-intro.adoc[]
include::1.0@scala-sdk:howtos:partial$n1ql-getting-started.adoc[]

== A Simple Query
Here's the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,scala]
----
include::example$Queries.scala[tag=simple,indent=0]
----

(Note that we won't be covering the N1QL language itself in any detail here, but if you're familiar with SQL you'll see it's very similar.)

The Scala SDK returns `Try` rather than throwing exceptions, to allow you to handle errors in a functional way.  A `Try` can either be a `Success(QueryResult)` if the N1QL statement was successfully executed, or `Failure(Throwable)` if something went wrong.  It can be pattern matched on like this:

[source,scala]
----
include::example$Queries.scala[tag=simple-results,indent=0]
----

The returned `QueryResult` contains an `allRowsAs[T]` method, allowing the results to be converted into something useful.  The above
example demonstrates returning the results as `JsonObject`, the JSON library built-in to the Scala SDK.

Other things allRowsAs can convert to are:

* `io.circe.Json` from the popular Scala JSON library https://circe.github.io/circe/[Circe]
* Similar support is included for other excellent JSON libraries: https://github.com/lihaoyi/upickle[uPickle/uJson], https://github.com/playframework/play-json[Play Json], https://github.com/typelevel/jawn[Jawn], and https://github.com/json4s/json4s[Json4s].
* Scala case classes.  A tiny amount of boilerplate is needed to support this: see xref:kv-operations.adoc[Key-Value Operations] for details.
* `String`
* `Array[Byte]`

Please see xref:json.adoc[this guide] for more information on the supported ways of working with JSON.

Of course, it wouldn't be Scala if we couldn't elegantly combine the operations above more concisely:

[source,scala]
----
include::example$Queries.scala[tag=get-rows,indent=0]
----

[NOTE]
=====
Most of the examples here use the simplest of the three APIs provided by the Scala SDK, which blocks until the operation is performed.  There's also an asynchronous API that is based around Scala `Future`, and a
streaming reactive API, for which we'll see an example later.
=====

include::1.0@scala-sdk:howtos:partial$n1ql-placeholders.adoc[]
include::1.0@scala-sdk:howtos:partial$n1ql-scan-consistency.adoc[]

== Returning Results as Case Classes
// TODO test this
The Scala SDK supports returning N1QL results directly as Scala case classes.

A small amount of boilerplate is required to tell the SDK how to convert your case class to/from JSON.  There are more details
available xref:json.adoc#case-classes[here], but the short version is to add a `Codec` in the case class's companion object like this:

[source,scala]
----
include::example$Queries.scala[tag=codec,indent=0]
----

Now you're free to pull out the results directly as your case class:

[source,scala]
----
include::example$Queries.scala[tag=case-classes,indent=0]
----

== Streaming Large Result Sets
As mentioned earlier, the Scala SDK provides three SDKs (documented further on xref:howtos:multiple-apis.adoc[Choosing an API]):

* The blocking API you've seen so far, that returns a `QueryResult` containing all rows.

* An async API that returns a `Future[QueryResult]`, which also contains all rows.  This can be accessed like this:

[source,scala]
----
include::example$Queries.scala[tag=async,indent=0]
----

* A reactive API, that can be used to stream rows.

The former two APIs buffer all rows in-memory until they can be returned to you.  With smaller queries this is likely to be fine, but for large data sets this could lead to Java `OutOfMemoryError` exceptions.

The recommended solution is to use the reactive API.  Reactive programming is a sophisticated paradigm that is rapidly gaining popularity for its ability to handle, amongst other things, streaming large amounts of data over fallible networks, while allowing error handling and backpressure.

The Scala SDK exposes primitives from the https://projectreactor.io/[Project Reactor] library, most notably `Mono` and `Flux`.  We strongly recommend https://projectreactor.io/learn[learning] a little of this library first, and the following examples will assume basic familiarity with Reactor.

[NOTE]
You'll see both `reactor.core.scala.publisher` and `reactor.core.publisher` imports available for Reactor.  Use the former, it is the Scala-optimized variant that the Scala SDK will return.

Here's how to perform a query and stream the results using the reactive API:

[source,scala]
----
include::example$Queries.scala[tag=reactive,indent=0]
----

include::1.0@scala-sdk:howtos:partial$n1ql-additional-resources.adoc[]
