= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.4/com/couchbase/client/scala/index.html[API docs].

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Scala SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

[source,scala]
----
include::example$ClusterResources.scala[tag=managers,indent=0]
----

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.bucket(name)` before you can use cluster-level managers.


== Creating and Removing Buckets

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.

The `CreateBucketSettings` and `BucketSettings` classes are used for creating and updating buckets.
`BucketSettings` is also used for exposing information about existing buckets.

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available for `CreateBucketSettings` and `BucketSettings`.
The "Updatable" column indicates whether the parameter may only be specified when creating a bucket, or whether it may be updated after creation.

[cols="30,30,28,12"]
|====
| Name | Type | Description | Updatable

| `name` | `String` | The name of the bucket, required for creation. | false
| `flushEnabled` | `boolean` | Enables flushing to be performed on this bucket (see the <<flushing>> section below). | true
| `replicaIndexes` | `boolean` | Whether or not to replicate indexes. | false
| `ramQuotaMB` | `int` | How much memory should each node use for the bucket, required for creation. | true
| `numReplicas` | `int` | The number of replicas to use for the bucket. | true
| `bucketType` | `BucketType` | The type of the bucket, required for creation. | false
| `ejectionMethod` | `EjectionMethod` | The type of the ejection to use for the bucket, defaults to `ValueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `maxTTL` | `int` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `compressionMode` | `CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `conflictResolutionType` | `ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `SequenceNumber` | false
|====

The following example creates a "hello" bucket:

[source,scala]
----
include::example$ClusterResources.scala[tag=bucket,indent=0]
----

We can now get this bucket and update it to enable Flush:

[source,scala]
----
include::example$ClusterResources.scala[tag=flush,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,scala]
----
include::example$ClusterResources.scala[tag=drop,indent=0]
----

[#flushing]
== Flushing Buckets

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `Flush` method:

[source,scala]
----
include::example$ClusterResources.scala[tag=flush-real,indent=0]
----

== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/manager/collection/index.html[`CollectionManager` and `AsyncCollectionManager` API documentation]
for further details.

[source,scala]
----
include::example$CollectionManagerExample.scala[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,scala]
----
include::example$CollectionManagerExample.scala[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,scala]
----
include::example$CollectionManagerExample.scala[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,scala]
----
include::example$CollectionManagerExample.scala[tag=drop-collection,indent=0]

include::example$CollectionManagerExample.scala[tag=drop-scope,indent=0]
----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with xref:server:learn:security/roles.adoc#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,scala]
----
include::example$CollectionManagerExample.scala[tag=scopeAdmin, indent=0]
----

== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs:

[source,scala]
----
include::example$ClusterResources.scala[tag=index-managers,indent=0]
----

// * Query

// * Search - note & link to FTS page & API?

== View Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on the `ViewIndexManager` instance:

[source,scala]
----
include::example$ClusterResources.scala[tag=view-manager,indent=0]
----

The following example upserts a design document with two views:

[source,scala]
----
include::example$ClusterResources.scala[tag=view-upsert,indent=0]
----

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespace.Development`, the other option is `DesignDocumentNamespace.Production`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,scala]
----
include::example$ClusterResources.scala[tag=view-get,indent=0]
----

We've created the design document using `DesignDocumentNamespace.Development` and now want to push it to production, we can do this with:

[source,scala]
----
include::example$ClusterResources.scala[tag=view-push,indent=0]
----

To remove this design document:

[source,scala]
----
include::example$ClusterResources.scala[tag=view-remove,indent=0]
----
