= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
// :page-aliases: ROOT:managing-clusters
:page-toclevels: 2

// API refs
:bucket-api-reference: pass:q[BucketManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#buckets:com.couchbase.client.scala.manager.bucket.BucketManager[`Cluster.buckets`]]
:user-api-reference: pass:q[UserManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#users:com.couchbase.client.scala.manager.user.UserManager[`Cluster.users`]]
:query-api-reference: pass:q[QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#queryIndexes:com.couchbase.client.scala.manager.query.QueryIndexManager[`Cluster.queryIndexes`]]
:analytics-api-reference: pass:q[AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#analyticsIndexes:com.couchbase.client.scala.manager.analytics.AnalyticsIndexManager[`Cluster.analyticsIndexes`]]
:search-api-reference: pass:q[SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Cluster.html#searchIndexes:com.couchbase.client.scala.manager.search.SearchIndexManager[`Cluster.searchIndexes`]]
:collection-api-reference: pass:q[CollectionManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Bucket.html#collections:com.couchbase.client.scala.manager.collection.CollectionManager[`Bucket.collections`]]
:view-api-reference: pass:q[ ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/Bucket.html#viewIndexes:com.couchbase.client.scala.manager.view.ViewIndexManager[`Bucket.viewIndexes`]]

// one-view-update-warning common partial
:upsertDesignDocument: pass:q[`upsertDesignDocument` method]
:getDesignDocument: pass:q[`getDesignDocument`]


[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/index.html[API docs].

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Scala SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* {bucket-api-reference}
* {user-api-reference} -- see the xref:sdk-user-management-example.adoc[User Management page]
* {query-api-reference} 
* {analytics-api-reference}
* {search-api-reference}
* {collection-api-reference}
* {view-api-reference}

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `Cluster.bucket(name)` before you can use cluster-level managers.

== Bucket Management

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.

The `CreateBucketSettings` and `BucketSettings` classes are used for creating and updating buckets.
`BucketSettings` is also used for exposing information about existing buckets.

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available for `CreateBucketSettings` and `BucketSettings`.
The "Updatable" column indicates whether the parameter may only be specified when creating a bucket, or whether it may be updated after creation.

[cols="30,30,28,12"]
|====
| Name | Type | Description | Updatable

| `name` | `String` | The name of the bucket, required for creation. | false
| `flushEnabled` | `boolean` | Enables flushing to be performed on this bucket (see the <<Flushing Buckets>> section below). | true
| `replicaIndexes` | `boolean` | Whether or not to replicate indexes. | false
| `ramQuotaMB` | `int` | How much memory should each node use for the bucket, required for creation. | true
| `numReplicas` | `int` | The number of replicas to use for the bucket. | true
| `bucketType` | `BucketType` | The type of the bucket, required for creation. | false
| `ejectionMethod` | `EjectionMethod` | The type of the ejection to use for the bucket, defaults to `ValueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `maxTTL` | `int` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `compressionMode` | `CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `conflictResolutionType` | `ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `SequenceNumber` | false
|====

The following example creates a "hello" bucket:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=bucket,indent=0]
----

We can now get this bucket and update it to enable Flush:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=flush,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=drop,indent=0]
----

=== Flushing Buckets

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `Flush` method:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=flush-real,indent=0]
----

== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/manager/collection/index.html[`CollectionManager` and `AsyncCollectionManager` API documentation]
for further details.

[source,scala]
----
include::devguide:example$scala/CollectionManagerExample.scala[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,scala]
----
include::devguide:example$scala/CollectionManagerExample.scala[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,scala]
----
include::devguide:example$scala/CollectionManagerExample.scala[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,scala]
----
include::devguide:example$scala/CollectionManagerExample.scala[tag=drop-collection,indent=0]

include::devguide:example$scala/CollectionManagerExample.scala[tag=drop-scope,indent=0]
----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with xref:server:learn:security/roles.adoc#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,scala]
----
include::devguide:example$scala/CollectionManagerExample.scala[tag=scopeAdmin, indent=0]
----


// see also https://issues.couchbase.com/browse/CBSE-16834 


== Index Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=index-management-intro]

=== QueryIndexManager

The `QueryIndexManager` interface contains the means for managing indexes used for queries. +
It can be accessed via `Cluster.queryIndexes`.

[source,scala]
----
include::devguide:example$scala/QueryIndexManagerExample.scala[tag=creating-index-mgr,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index, restricted to a named scope and collection, by calling the `createPrimaryIndex()` method.
Note that you cannot provide a named scope or collection separately, both must be set for the `QueryIndexManager` to create an index on the relevant keyspace path. 

.Creating a primary index

[source,scala]
----
include::devguide:example$scala/QueryIndexManagerExample.scala[tag=primary,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply pass an `indexName` argument to `createPrimaryIndex()`.

You may have noticed that the example also sets the `ignoreIfExists` boolean flag. 
When set to `true`, this optional argument ensures that an error is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index

[source,scala]
----
include::devguide:example$scala/QueryIndexManagerExample.scala[tag=secondary,indent=0]
----

The `createIndex()` method requires an index name to be provided, along with the fields to create the index on.
Like the _primary_ index, you can restrict a _secondary_ index to a named scope and collection.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `deferred` boolean option, and set it to `true`.

.Deferring index creation

[source,scala]
----
include::devguide:example$scala/QueryIndexManagerExample.scala[tag=defer-indexes,indent=0]
----

To delete a query index you can use the `dropIndex()` or `dropPrimaryIndex()` methods. 
Which one you use depends on the type of query index you wish to drop from the database.

.Deleting an index

[source,scala]
----
include::devguide:example$scala/QueryIndexManagerExample.scala[tag=drop-primary-or-secondary-index,indent=0]
----

// * Search - note & link to FTS page & API?



== Eventing Management

// some SDKs (PHP, Ruby, Kotlin, C++) because they don't currently have any eventing management. 


////
https://issues.couchbase.com/browse/CBD-4930

While investigating PYCBC-1277 and MB-51480 we saw the new function_scope field that was introduced with 7.1 and had to workaround it temporarily. The "function_scope" acts as a "grouping tag" or "namespace" and is now required due to recent changed for RBAC. Without this specified, the "*" default will be assumed and only the Admin can perform Eventing Management operations.
////




== View Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on the `ViewIndexManager` instance:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=view-manager,indent=0]
----

The following example upserts a design document with two views:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=view-upsert,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespace.Development`, the other option is `DesignDocumentNamespace.Production`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=view-get,indent=0]
----

We've created the design document using `DesignDocumentNamespace.Development` and now want to push it to production, we can do this with:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=view-push,indent=0]
----

To remove this design document:

[source,scala]
----
include::devguide:example$scala/ClusterResources.scala[tag=view-remove,indent=0]
----
