= Authenticating against Couchbase Server
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: sdk-authentication-overview

[abstract]
As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,scala]
----
include::example$Auth.scala[tag=basic,indent=0]
----

Couchbase uses Role Base Access Control (RBAC), and has since Server 5.0 was released.
For a general overview of Couchbase-Server authorization, see xref:6.5@server:learn:security/authorization-overview.adoc[Authorization].
For a list of available roles and corresponding privileges, see xref:6.5@server:learn:security/roles.adoc[Roles].

In the SDK docs, many examples will use the full _Administrator_ role for convenience, but this is rarely a good idea on a production machine, so reference the above links to find best practice for the needs of your application.
RBAC is also implemented by the Community Edition of Couchbase Server, but with fewer roles -- see the xref:6.5@server:learn:security/roles.adoc[Roles overview].


== Certificate Authentication


Couchbase Server supports the use of X.509 certificates to authenticate clients (only available in the Enterprise Edition, not the Community Edition).
This allows authenticated users to access specific resources by means of the data service, in Couchbase Server 5.1 and up, and all other services in more recent releases of Couchbase Data Platform.

The process relies on a certificate authority, for the issuing of certificates that validate identities.
A certificate includes information such as the name of the entity it identifies, an expiration date, the name of the authority that issued the certificate, and the digital signature of the authority.
A client attempting to access Couchbase Server can present a certificate to the server, allowing the server to check the validity of the certificate.
If the certificate is valid, the user under whose identity the client is running, and the roles assigned that user, are verified.
If the assigned roles are appropriate for the level of access requested to the specified resource, access is granted.

For a more detailed conceptual description of using certificates, see xref:6.5@server:learn:security/certificates.adoc[Certificates].

== Authenticating a Scala Client by Certificate

For sample procedures whereby certificates can be generated and deployed, see xref:6.5@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed.
That is, a cluster certificate has been created and installed on the server, a client certificate has been created, and it is stored in a JVM keystore along with the cluster's certificate.

[source,scala]
----
include::example$Auth.scala[tag=auth,indent=0]
----

== LDAP

If you are on a network where access is controlled by LDAP, the SDK will work transparently with it.
No special configuration is needed.
