= Transcoders & Non-JSON Documents
:description: The Scala SDK supports common JSON document requirements out-of-the-box.

[abstract]
{description}
Custom transcoders and serializers provide support for applications needing to perform advanced operations, including supporting non-JSON data.

The Scala SDK uses the concepts of transcoders and serializers, which are used whenever data is sent to or retrieved from Couchbase Server.

When sending data to Couchbase, the SDK passes the object being sent to a transcoder.
The transcoder can either reject the object as being unsupported, or convert it into a `byte[]` and a Common Flag.
The Common Flag specifies whether the data is JSON, a non-JSON string, or raw binary data.
It may, but does not have to, use a serializer to perform the byte conversion.

Serializers are discovered at compile-time: if the application is sending type `T`, the compiler will look for a `JsonSerializer[T]`.
Similarly when the application is receiving data to a desired type `T`, the compiler will look for a `JsonDeserializer[T]`.
There are JsonSerializer and JsonDeserializer implementations provided for many types, including several popular third-party JSON libraries, and it is easy to add more.

On retrieving data from Couchbase, the fetched `byte[]` and Common Flag are passed to a transcoder.
The transcoder converts the bytes into a concrete class (the application specifies the required type) if possible.  
It may use a serializer (the `JsonDeserializer[T]`) for this.

So, while a JsonSerializer[T] and JsonDeserializer[T] will always be found - the code will not compile if not - they are not necessarily used.
It is down to the transcoder to make this choice.

NOTE: Many applications will not need to be aware of transcoders and serializers, as the defaults support most standard JSON use cases.
The information in this page is only needed if the application has an advanced use-case, likely involving either non-JSON data, or a requirement for a particular JSON serialization library.
For examples of many common JSON use cases see xref:howtos:json.adoc[JSON Libraries].

== Default Behaviour
The `ClusterEnvironment` contains a global transcoder, which by default is `JsonTranscoder`.


On sending data of type `T` to Couchbase, a `JsonSerializer[T]` will be found by the compiler.
If it cannot be found, the program will not be compiled.
`JsonTranscoder` will send objects to that serializer to convert into a `byte[]`.
The serialized bytes are then sent to the Couchbase Server, along with a Common Flag of JSON.

`JsonTranscoder` will pass any `T` to its serializer, apart from a `byte[]`.
It will reject this with a `Failure(IllegalArgumentException)`, as it is ambiguous how it should be handled.

On retrieving data from Couchbase into a desired type `T`, a `JsonDeserializer[T]` will be found by the compiler.
`JsonTranscoder` passes the fetched `byte[]` and Common Flag to that serializer to convert into a `T`.

This table summarizes that information, and this more concise form will be used to describe the other transcoders included in the SDK.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|String
|Results of serializer
|JSON

|byte[]
|Failure(IllegalArgumentException)
|-

|Other `T`
|Results of serializer
|JSON
|===

The default `JsonSerializer` and `JsonDeserializer` provided handle objects of type `T` as follows:

[cols="2", options="header"]
|===
|Type of `T`
|Serialized

|String
|Into/from JSON with the high-performance JSON library https://github.com/FasterXML/jackson[Jackson]

|byte[]
|Passed through (no serialization)

|`JsonObject`, `JsonArray`, `JsonObjectSafe`, `JsonArraySafe`
|Into/from JSON using Jackson

|`Boolean`
|Into/from a JSON representation directly ('true' or 'false')

|Other primitives (`Int`, `Double`, `Long`, `Short`)
|Into/from a JSON representation directly

|`ujson.Value` from http://www.lihaoyi.com/upickle/[µPickle]
|Into/from JSON using the µPickle library

|`io.circe.Json` from https://circe.github.io/circe/[Circe]
|Into/from JSON using the Circe library

|`play.api.libs.json.JsValue` from https://github.com/playframework/play-json[Play JSON]
|Into/from JSON using the Play JSON library

|`org.json4s.JsonAST.JValue` from http://json4s.org/[Json4s]
|Into/from JSON using the Json4s library

|`org.typelevel.jawn.ast.JValue` from https://github.com/typelevel/jawn[Jawn]
|Into/from JSON using the Jawn library

|Scala case classes
|Into/from JSON with a small amount of boilerplate to automatically generate a JsonSerializer
|===

There are concrete examples of using these on the xref:json.adoc[JSON Libraries] page.  
Note that the Scala SDK only has an optional dependency on Circe, Json4s, et al, so those libraries not be pulled into your application.

== RawJsonTranscoder
The RawJsonTranscoder provides the ability for the application to explicitly specify that the data they are storing or retrieving is JSON.
This transcoder does not accept a serializer, and always performs straight pass through of the data to the server.
This enables the application to avoid unnecessary parsing costs when they are certain they are using JSON data.

It only accepts Strings and `byte[]`.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|String
|Passthrough
|JSON

|byte[]
|Passthrough
|JSON

|Other `T`
|Failure(IllegalArgumentException)
|-
|===

Say we want to serialize and deserialize some data with the JSON library uPickle[https://github.com/lihaoyi/upickle], and have the Scala SDK just passthrough the serialized data to and from Couchbase.
We will look at better ways of doing this later, but here is one approach using `RawJsonTranscoder`.

Since uPickle has already done the serialization work, we don't want to use the default `JsonTranscoder`, as this will run the provided bytes needlessly through `DefaultJsonSerializer` (Jackson).
Instead, RawJsonTranscoder is used, which just passes through the serialized bytes, and stores them in Couchbase with the JSON Common Flag set.
Similarly, the same transcoder is used on reading the document, so the raw bytes can be retrieved in a String without going through `DefaultJsonSerializer` (Jackson).

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=json,indent=0]
----


== Non-JSON Transcoders
It is most common to store JSON with Couchbase.
However, it is possible to store non-JSON documents, such as raw binary data, perhaps using an concise binary encoding like https://msgpack.org[MessagePack] or https://cbor.io/[CBOR], in the Key-Value store.

NOTE: It's important to note that the Couchbase Data Platform includes multiple components other than the Key-Value store -- including Query and its indexes, FTS, Analytics, and Eventing -- and these are optimized for JSON and will either ignore or provide limited functionality with non-JSON documents.

Also note that some simple data types can be stored directly as JSON, without recourse to non-JSON transcoding.
A valid JSON document can be a simple integer (`42`), string (`"hello"`), array (`[1,2,3]`), boolean (`true`, `false`) and the JSON `null` value.

=== RawStringTranscoder
The RawStringTranscoder provides the ability for the user to explicitly store and retrieve raw string data with Couchbase.
It can be used to avoid the overhead of storing the string as JSON, which requires two bytes for double quotes, plus potentially more for escaping characters.

Note that this transcoder does not accept a serializer, and always performs straight passthrough of the data to the server.
It only accepts Strings.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|String
|Passthrough
|String

|byte[]
|Failure(IllegalArgumentException)
|-

|Other `T`
|Failure(IllegalArgumentException)
|-
|===

Here’s an example of using the `RawStringTranscoder`:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=string,indent=0]
----

=== RawBinaryTranscoder
The RawBinaryTranscoder provides the ability for the user to explicitly store and retrieve raw byte data to Couchbase.
The transcoder does not perform any form of real transcoding, and does not take a serializer, but rather passes the data through and assigns the appropriate binary Common Flag.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|String
|Failure(IllegalArgumentException)
|-

|byte[]
|Passthrough
|Binary

|Other `T`
|Failure(IllegalArgumentException)
|-
|===

Here’s an example of using the `RawBinaryTranscoder`:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=binary,indent=0]
----

== Custom Transcoders and Serializers
More advanced transcoding needs can be accomplished if the application implements their own transcoders and serializers.

=== Creating a Custom Serializer
Say we have a Scala case class, `MyUser`, that we want to easily convert to & from JSON to store in Couchbase.
The Scala SDK already provides support for this (see xref:howtos:json.adoc[JSON Libraries]), but perhaps for some reason we want to use the JSON library https://github.com/lihaoyi/upickle[uPickle] for this instead.
First we need a `JsonSerializer[User]` and `JsonDeserializer[User]`, which are simple to write:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=ujson,indent=0]
----

Both of these are marked `implicit object` and inside `object MyUser` so the compiler can find them.
They will now be picked up by the compiler and used automatically:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=ujson-used,indent=0]
----

Note we don't need to change the transcoder for this example.
The <<Default Behaviour,table for `JsonTranscoder`>> shows that it already does what we need: on serialization (in the `upsert`), it passes the `MyUser` object to the compiler-found serializer (`UserSerializer`) and stores the result in Couchbase with the JSON common flag.
And on deserialization (in the `contentAs`), the raw bytes are passed to `UserDeserializer`, and resulting `MyUser` passed back to the application.

=== Selecting a Serializer
What if there are multiple serializers that could be used for an object, and the application needs to select one?

The serializer is an implicit argument to any operation that requires one, and the compiler-chosen selection can be overwritten by the application like this:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=overloaded1,indent=0]
----

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=overloaded2,indent=0]
----

=== Creating a Custom Transcoder
Let’s look at a more complex example: encoding the JSON alternative, https://msgpack.org[MessagePack].
MessagePack is a compact binary data representation, so it should be stored with the binary Common Flag.
The Common Flag is chosen by the transcoder, and none of the existing transcoders matches our needs (`RawBinaryTranscoder` does set the binary flag, but it passes data through directly rather than using a serializer).  
So we need to write one.

Start by creating a new serializer and deserializer for our case class, that uses MessagePack:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=msgpack-serializer,indent=0]
----

And now create a transcoder that sets the binary Common Flag when storing the data:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=msgpack-transcoder,indent=0]
----

Note this transcoder is completely independent to MessagePack.
All it does is pass data to and from a serializer, and set a Binary Common Flag.

Now we can use the new transcoder and serializer to seamlessly store MessagePack data in Couchbase Server:

[source,scala]
----
include::devguide:example$scala/Transcoding.scala[tag=msgpack-encode,indent=0]
----

== Further reading

* For _Common flags_, setting the data format used, see the xref:ref:data-structures.adoc#common-flags[Data Structures reference].
* _Format flags_ for ancient SDKs are still available for compatibility, if you are porting a long-lived legacy app. 
See the xref:ref:data-structures.adoc#legacy-formats[Legacy formats reference].
* If you want to work with binary documents and our Search service, you might like to take a look at https://github.com/khanium/couchbase-fts-binary




