= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Scala SDK
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

include::project-docs:partial$attributes.adoc[]

[abstract]
Features available in different SDK versions, and compatibility between Server and SDK.
Plus notes on Cloud, networks, and AWS Lambda.


The Couchbase Scala SDK 1.1 Client supports Scala 2.12
// and 2.13.

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Scala SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | SDK 1.0, 1.1 | 1.2

| *Server 5.0-5.5*
| *◎*
| *◎*

| *Server 6.0*
| *✔*
| *✔*

| *Server 6.5-6.6*
| *✔*
| *✔*

| *Server 7.0*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


[#jdk-compat]
== JDK Version Compatibility

The Scala SDK is tested with Oracle JDK and OpenJDK.
Other JDK implementations might work but are not tested and are unsupported.
We recommend running the latest LTS version (i.e. at the time of writing JDK 11) with the highest patch version available.

The following JDK releases are supported:

* OpenJDK 11 with HotSpot JVM (recommended)
* Oracle JDK 11 (recommended)
* OpenJDK 1.8 with HotSpot JVM
* Oracle JDK 1.8

Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,7,5,6,5"]
|===
| | Server 5.0, 5.1, & 5.5 | Server 6.0 | Server 6.5 & 6.6 | Server 7.0

| Enhanced Durability
| Not Supported
3+| Since 1.0

| Durable Writes
2+| Not Supported
2+| Since 1.0

| Analytics
| Not Supported
3+| Since 1.0

| Default Collections
2+| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since 1.0.10

| Scope-Level N1QL Queries & all Collections features
3+| Not Supported
| Since SDK 1.2.0

| Request Tracing
2+| Not Supported
2+| Since SDK 1.2.0
|===

include::{version-server}@sdk:shared:partial$network-requirements.adoc[]



== Spring Data Couchbase Compatibility

https://projects.spring.io/spring-data-couchbase/[Spring Data Couchbase^] uses the Java SDK underneath and as a result is also provides different compatibilities with Couchbase Server.
The following table provides an overview.

.Recommended Spring Data Couchbase per Server Version Matrix
[#table_spring_versions]
|===
| | SDC 3.x | SDC 4.0 - 4.2

| _Status ->_
| _SDK 2.x only_
| _New Features, Active Development_

| *Server 5.x*
| SDK 2.x
| *Not Compatible*

| *Server 6.0*
| SDK 2.x
| *Recommended*

| *Server 6.5 & 6.6*
| SDK 2.x
| *Recommended*

| *Server 7.0*
| Not Supported
| *Recommended*
|===

NOTE: Check the Spring Data Couchbase's compile dependencies -- older versions may link an out-of-date version of the SDK in their dependencies list, although a supported version should be in the `updates`.
Please make sure that you are using a supported version of the Couchbase Scala SDK, prefereably the latest version, which will contain any available bug fixes.
Using the latest Spring Data Couchbase should ensure that this is so.


include::{version-server}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
