= Couchbase Scala SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-scala-sdk

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Scala Client.

These pages cover the 1.0 releases of the Couchbase Scala SDK, which follows the Couchbase 3.0 SDK API. 

== Version 1.0.2 (3 March 2020)

Version 1.0.2 is the third release of the Scala SDK, bringing enhancements and bugfixes over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.2/scaladocs/com/couchbase/client/scala/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.2**
* com.couchbase.client:**core-io:2.0.3**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-813[JVMCBC-813]:
Improved error message for bucket is missing.
* http://issues.couchbase.com/browse/JVMCBC-815[JVMCBC-815]:
Check if key exceeds size limits.
* http://issues.couchbase.com/browse/JVMCBC-818[JVMCBC-818]:
Trimmed netty stack in connect failures for more readable output.
* http://issues.couchbase.com/browse/JVMCBC-819[JVMCBC-819]:
Distinguished bucket not found in select bucket failures.
* http://issues.couchbase.com/browse/JVMCBC-823[JVMCBC-823]:
Added a global component to the core id.
* http://issues.couchbase.com/browse/JVMCBC-825[JVMCBC-825]:
Support added for new VATTR HELLO flag.
* http://issues.couchbase.com/browse/SCBC-43[SCBC-43]:
With huge thanks to our community, who submitted the patch, it is now possible to build versions of the SDK for 2.11 and 2.13.
Couchbase only officially provides, tests and supports a Scala 2.12 build currently, but users are welcome to build their own jars for 2.11 or 2.13 following the https://github.com/couchbase/couchbase-jvm-clients[README instructions].

=== Bug Fixes

* http://issues.couchbase.com/browse/SCBC-200[SCBC-200]:
Dependencies now correctly shaded.
* http://issues.couchbase.com/browse/SCBC-207[SCBC-207]:
Exists no longer returns wrong value if executed right after remove.
* http://issues.couchbase.com/browse/SCBC-216[SCBC-216]:
Properly clear cache when repreparing/retrying query.
* http://issues.couchbase.com/browse/JVMCBC-824[JVMCBC-824]:
Native Netty transports not included, resulting in fallback to default implementation.  This was a regression in the 2.0.2 core-io release.
* http://issues.couchbase.com/browse/JCBC-1600[JCBC-1600]:
Using expiry together with document flags on a Sub-Document `mutateIn` no longer causes an incorrect flags field to be sent.

== Version 1.0.1 (5th February 2020)

Version 1.0.1 is the second release of the 1.0 series, bringing new features, enhancements, and bugfixes over the last stable release.

=== Stability Enhancements & Bug Fixes
* https://issues.couchbase.com/browse/SCBC-192[SCBC-192]:
All scaladoc warnings fixed.
* https://issues.couchbase.com/browse/SCBC-193[SCBC-193]:
When creating buckets, numReplicas can now be specified.

=== New Features & Enhancements
* https://issues.couchbase.com/browse/SCBC-190[SCBC-190]:
Exposed enableDnsSrv parameter on `IoConfig()`, allowing DNS SRV to be used.
* https://issues.couchbase.com/browse/SCBC-204[SCBC-204]:
Added support for new server flag `createAsDeleted` -- for internal use only.
* https://issues.couchbase.com/browse/SCBC-201[SCBC-201]:
Exposed Java core environment through Scala ClusterEnvironment, allowing the event-bus to be accessed.
* https://issues.couchbase.com/browse/SCBC-198[SCBC-198]:
Exposed environment getter through cluster. 
This allows a constructed environment to be shutdown without having to maintain a reference to it.

== Version 1.0.0 (17th January 2020)

This is the first General Availability (GA) release of the new Couchbase Scala SDK.
It brings a large number of improvements, bug-fixes and API changes from the previous beta release.

=== Stability Enhancements & Bug Fixes
* https://issues.couchbase.com/browse/SCBC-147[SCBC-147]:
QueryIndexManager should return only GSI indexes
* https://issues.couchbase.com/browse/SCBC-151[SCBC-151]:
Make sure all reactive ops are deferred; this ensures that `collection.reactive.remove(...)` won't perform a remove until the SMono is subscribed to
* https://issues.couchbase.com/browse/SCBC-154[SCBC-154]:
Make UserManager handle pre-LDAP clusters
* https://issues.couchbase.com/browse/SCBC-157[SCBC-157]:
Handle projections of objects inside arrays correctly
* https://issues.couchbase.com/browse/SCBC-158[SCBC-158]:
Handle 'too many set inserts' internal error while converting JSON to case classes
* https://issues.couchbase.com/browse/SCBC-163[SCBC-163]:
ViewQuery does not send request
* https://issues.couchbase.com/browse/SCBC-167[SCBC-167]:
Fix FTS consistentWith
* https://issues.couchbase.com/browse/SCBC-174[SCBC-174]:
ReactiveCollection KV operations now do ClientVerified Observe check
* https://issues.couchbase.com/browse/SCBC-182[SCBC-182]:
QueryOptions missing setters

=== New Features & Enhancements
* https://issues.couchbase.com/browse/SCBC-190[SCBC-190]:
Expose enableDnsSrv parameter on `IoConfig()`, allowing DNS SRV to be used
* https://issues.couchbase.com/browse/SCBC-192[SCBC-192]:
All scaladoc warnings fixed
* https://issues.couchbase.com/browse/SCBC-204[SCBC-204]:
Add support for new server flag `createAsDeleted`, for internal use only

=== API Changes
* https://issues.couchbase.com/browse/SCBC-159[SCBC-159]:
Fix semantics of datastructures so they behave more like Scala collections
* https://issues.couchbase.com/browse/SCBC-162[SCBC-162]:
All ReactiveBinaryCollection methods should return SMono
* https://issues.couchbase.com/browse/SCBC-164[SCBC-164]:
Align with latest view RFC
* https://issues.couchbase.com/browse/SCBC-136[SCBC-136]:
Track all Java environment changes
* https://issues.couchbase.com/browse/SCBC-138[SCBC-138]:
Replace management API Scala exceptions with core ones
* https://issues.couchbase.com/browse/SCBC-139[SCBC-139]:
GetSelecter is using incorrect exceptions
* https://issues.couchbase.com/browse/SCBC-155[SCBC-155]:
Rename *master to *active throughout
* https://issues.couchbase.com/browse/SCBC-187[SCBC-187]:
Remove scopeExists and collectionExists from CollectionManager
* https://issues.couchbase.com/browse/SCBC-188[SCBC-188]:
Align UserAndMetadata with latest RFC


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 1.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].
