= Couchbase Scala SDK Installation
:description: Installation instructions for the Couchbase Scala Client.
:navtitle: Full Installation
:page-partial:
:page-toclevels: 2

[abstract]
{description}


This page gives full installation instructions for the {name-sdk}.
In most cases, the xref:hello-world:start-using-sdk.adoc[Quickstart Guide] should be enough to get you up and running if you're in a hurry.


== Prerequisites

The Scala SDK is tested against LTS versions of Oracle JDK and OpenJDK -- see our xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].
The underlying OS normally makes no difference, but library incompatibilities in Alpine Linux makes a xref:project-docs:compatibility.adoc#alpine-linux-compatibility[workaround] necessary for this OS.

The Couchbase Scala SDK 3.9 Client supports Scala 2.12, 2.13, and 3.3 through 3.7 (inclusive).


== Installing the SDK

The Couchbase Scala SDK is available on the Maven repository, packaged for Scala 2.12, 2.13, and 3.

=== With SBT Projects

It can be included in your SBT build like this:


[source,sbt,subs="+attributes"]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "{sdk_current_version}"
----

This will automatically use the correct build for your Scala version.

=== With Gradle Projects

It can be included in your `build.gradle` like this for 2.12:

[source,groovy,subs="+attributes"]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.12', version: '{sdk_current_version}'
}
----

or 2.13 or 3.3 through 3.7:

[source,groovy,subs="+attributes"]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_3', version: '{sdk_current_version}'
}
----

There is a dedicated 2.13 build too, but from the 3.9.0 release we recommended 2.13 users use the 3.x build instead.  
If the 2.13 build is explicitly desired, it can be included like this:

[source,groovy,subs="+attributes"]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.13', version: '{sdk_current_version}'
}
----

=== With Maven Projects

It can be included in your Maven `pom.xml` like this for 2.12:

[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.12</artifactId>
        <version>{sdk_current_version}</version>
    </dependency>
</dependencies>
----

or 2.13 or 3.3 through 3.7:

[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_3</artifactId>
        <version>{sdk_current_version}</version>
    </dependency>
</dependencies>
----

There is a dedicated 2.13 build too, but from the 3.9.0 release we recommended 2.13 users use the 3.x build instead. 
If the 2.13 build is explicitly desired, it can be included like this:

[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.13</artifactId>
        <version>{sdk_current_version}</version>
    </dependency>
</dependencies>
----


[snapshots]
== Using a Snapshot Version

Couchbase publishes pre-release snapshot artifacts to the Central Portal Snapshots Repository.
If you wish to use a snapshot version, you'll need to tell your build tool about this repository.

[{tabs}]
====
Maven::
+
--
.`*pom.xml*`
[source,xml]
----
<repositories>
    <repository>
        <name>Central Portal Snapshots</name>
        <id>central-portal-snapshots</id>
        <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----
--
Gradle (Groovy)::
+
--
.`*build.gradle*`
[source,groovy]
----
repositories {
    mavenCentral()
    maven {
        url "https://central.sonatype.com/repository/maven-snapshots/"
        mavenContent { snapshotsOnly() }
    }
}
----
--
====

== Further Reading

For those who spend little or no time using {name_platform}, but have to evaluate the platform, further installation and background help is available on the xref:hello-world:platform-help.adoc[{name_platform} Platform Introduction page].
