= Couchbase Scala SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-scala-sdk

== Installation

The Couchbase Scala SDK is available on the Couchbase Maven repository and can be included in your `build.gradle`
like this:

[source,groovy]
----
repositories {
    maven {
        url 'http://files.couchbase.com/maven2'
    }
}

dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.12', version: '1.0.0-beta.1'
}
----

Or into your Maven pom.xml:

[source,xml]
----
<repositories>
    <repository>
      <id>couchbase</id>
      <name>Couchbase Preview Repository</name>
      <url>http://files.couchbase.com/maven2</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.12</artifactId>
        <version>1.0.0-beta.1</version>
    </dependency>
</dependencies>
----

Or for SBT:

[source,sbt]
----
resolvers += "Couchbase Snapshots" at "http://files.couchbase.com/maven2"
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.0.0-beta.1"
----

== Version 1.0.0-alpha8 (30th September 2019)

This is the eighth pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-86[SCBC-86]:
Add Collection accessors for the data structures

=== API Changes

* https://issues.couchbase.com/browse/SCBC-91[SCBC-91]:
Rename expiration to expiry
* https://issues.couchbase.com/browse/SCBC-93[SCBC-93]:
Renamed GetFromReplicaResult to GetReplicaResult
* https://issues.couchbase.com/browse/SCBC-94[SCBC-94]:
Remove LookupInSpec.getFullDocument per RFC change.  Use `get("")` instead.
* https://issues.couchbase.com/browse/SCBC-96[SCBC-96]:
Rename shutdown to disconnect on *Cluster

== Version 1.0.0-alpha7 (2nd September 2019)

This is the seventh pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-59[SCBC-59]: Add user and groups management API
* https://issues.couchbase.com/browse/SCBC-31[SCBC-31]: Provide auto-generated clientContextId if not provided
* https://issues.couchbase.com/browse/SCBC-54[SCBC-54]: Make collections and scopes volatile
* https://issues.couchbase.com/browse/SCBC-25[SCBC-25]: Support multiple-value variants of arrayAppend et al. with Sub-Document
* https://issues.couchbase.com/browse/SCBC-72[SCBC-72]: Lookupin missing expiration option
* https://issues.couchbase.com/browse/SCBC-59[SCBC-59]: Add user and groups management API
* https://issues.couchbase.com/browse/SCBC-68[SCBC-68]: Add query service fast prepare support
* https://issues.couchbase.com/browse/SCBC-67[SCBC-67]: Add Datastructures v2 for "SDK3"
* https://issues.couchbase.com/browse/SCBC-64[SCBC-64]: Add bucket manager API

=== Deprecations and Removals

* https://issues.couchbase.com/browse/SCBC-57[SCBC-57]: Remove defaultCollection from scope

=== API Changes

During the alpha period we will where necessary make breaking changes to the API to enhance and improve it.

* https://issues.couchbase.com/browse/SCBC-35[SCBC-35]: Change Cluster.connect to return Try[Cluster].
To permit Cluster opening to return errors (for example, on a badly constructed connection string), now operations return a Try[Cluster].
* https://issues.couchbase.com/browse/SCBC-71[SCBC-71]: Remove either Codec or Codecs.
You can now write `implicit val codec: Codec[User] = Codec.codec[User]` without having to import both Codec and Codecs.
* https://issues.couchbase.com/browse/SCBC-28[SCBC-28]: Track RFC changes on getFromReplica

== Version 1.0.0-alpha6 (5th August 2019)

This is the sixth pre-release of the new Couchbase Scala SDK.

There are no new features, but improvements to the underlying core-io library provide increased stability and performance.

=== Deprecations and Removals

* https://issues.couchbase.com/browse/SCBC-50[SCBC-50]:	OpenTracing removed from API, as it is transitioning to OpenTelemetry currently.
Support for OpenTelemetry may be added at a later date.

== Version 1.0.0-alpha5 (5th July 2019)

This is the fifth pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-26[SCBC-26]:	Support consistentWith for query
* https://issues.couchbase.com/browse/SCBC-38[SCBC-38]:	Add prepared statement support

== Version 1.0.0-alpha4 (12th June 2019)

This is the fourth pre-release of the new Couchbase Scala SDK.

There are no new features, but improvements to the underlying core-io library provide increased stability and performance.

=== Deprecations and Removals

* https://issues.couchbase.com/browse/SCBC-41[SCBC-41]: Spatial Views are no longer supported, so the API is removed.

== Version 1.0.0-alpha3 (14th May 2019)

This is the third pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-15[SCBC-15]: 
Support for Full Text Search (FTS).
* https://issues.couchbase.com/browse/SCBC-12[SCBC-12]: 
Simplify the results of the query API, moving QueryAdditional to QueryMeta, and putting all non-results into QueryMeta.
* https://issues.couchbase.com/browse/SCBC-13[SCBC-13]: 
Further Query API simplifications, allowing all rows to be converted into the target type with rowsAs[T].
* https://issues.couchbase.com/browse/SCBC-22[SCBC-22]: 
A 2.11 build of the Scala library is now provided.
* https://issues.couchbase.com/browse/SCBC-11[SCBC-11]: 
Environment construction is now done with native Scala objects.

== Version 1.0.0-alpha2 (4th April 2019)

This is the second pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-5[SCBC-5], https://issues.couchbase.com/browse/SCBC-6[SCBC-6]: 
Significant updates for the subdoc API.
* https://issues.couchbase.com/browse/SCBC-8[SCBC-8]: 
Get ops in the reactive API now return Mono<Optional>.
* https://issues.couchbase.com/browse/SCBC-16[SCBC-16]: 
Added support for View queries.
* https://issues.couchbase.com/browse/SCBC-14[SCBC-14]: 
Added support for Analytics queries.

