= Couchbase Scala SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-scala-sdk

== Installation

The Couchbase Scala SDK is available on the Couchbase Maven repository and can be included in your `build.gradle`
like this:

[source,groovy]
----
repositories {
    maven {
        url 'http://files.couchbase.com/maven2'
    }
}

dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.12', version: '1.0.0-alpha.6'
}
----

Or into your Maven pom.xml:

[source,xml]
----
<repositories>
    <repository>
      <id>couchbase</id>
      <name>Couchbase Preview Repository</name>
      <url>http://files.couchbase.com/maven2</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.12</artifactId>
        <version>1.0.0-alpha.6</version>
    </dependency>
</dependencies>
----

Or for SBT:

[source,sbt]
----
resolvers += "Couchbase Snapshots" at "http://files.couchbase.com/maven2"
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.0.0-alpha.6"
----

== Version 1.0.0-alpha4 (12th June 2019)

This is the fourth pre-release of the new Couchbase Scala SDK.

There are no new features, but improvements to the underlying core-io library provide increased stability and performance.

=== Deprecations and Removals

* https://issues.couchbase.com/browse/SCBC-41[SCBC-41]: Spatial Views are no longer supported, so the API is removed.

== Version 1.0.0-alpha3 (14th May 2019)

This is the third pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-15[SCBC-15]: 
Support for Full Text Search (FTS).
* https://issues.couchbase.com/browse/SCBC-12[SCBC-12]: 
Simplify the results of the query API, moving QueryAdditional to QueryMeta, and putting all non-results into QueryMeta.
* https://issues.couchbase.com/browse/SCBC-13[SCBC-13]: 
Further Query API simplifications, allowing all rows to be converted into the target type with rowsAs[T].
* https://issues.couchbase.com/browse/SCBC-22[SCBC-22]: 
A 2.11 build of the Scala library is now provided.
* https://issues.couchbase.com/browse/SCBC-11[SCBC-11]: 
Environment construction is now done with native Scala objects.

== Version 1.0.0-alpha2 (4th April 2019)

This is the second pre-release of the new Couchbase Scala SDK.

=== New Features & Enhancements

* https://issues.couchbase.com/browse/SCBC-5[SCBC-5], https://issues.couchbase.com/browse/SCBC-6[SCBC-6]: 
Significant updates for the subdoc API.
* https://issues.couchbase.com/browse/SCBC-8[SCBC-8]: 
Get ops in the reactive API now return Mono<Optional>.
* https://issues.couchbase.com/browse/SCBC-16[SCBC-16]: 
Added support for View queries.
* https://issues.couchbase.com/browse/SCBC-14[SCBC-14]: 
Added support for Analytics queries.

