= Couchbase Scala SDK Installation
:description: Installation instructions for the Couchbase Scala Client.
:navtitle: Full Installation
:page-partial:
:page-topic-type: project-doc

[abstract]
{description}


The Couchbase Scala SDK allows Scala applications to access a Couchbase cluster.

== Prerequisites

The Scala SDK is tested against LTS versions of Oracle JDK and OpenJDK -- see our xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].
The underlying OS normally makes no difference, but library incompatibilities in Alpine Linux makes a xref:project-docs:compatibility.adoc#alpine-linux-compatibility[workaround] necessary for this OS.


== Installing the SDK

The Couchbase Scala SDK is available on the Maven repository, packaged for Scala 2.12 and 2.13.

=== With SBT Projects
It can be included in your SBT build like this:

[source,sbt]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.4.3"
----

This will automatically use the Scala 2.12 or 2.13 builds, as appropriate for your SBT project.

=== With Gradle Projects
It can be included in your `build.gradle` like this for 2.12:

[source,groovy]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.12', version: '1.4.3'
}
----

or 2.13:

[source,groovy]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.13', version: '1.4.3'
}
----

=== With Maven Projects

It can be included in your Maven `pom.xml` like this for 2.12:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.12</artifactId>
        <version>1.4.3</version>
    </dependency>
</dependencies>
----

or 2.13:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.13</artifactId>
        <version>1.4.3</version>
    </dependency>
</dependencies>
----
