= Couchbase Scala SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Scala Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-scala-sdk

// tag::all[]
[abstract]
{description}


== Version 1.2.6 (2 March 2021)
There are no changes at the Scala SDK layer in this release, but there are bugfixes and improvements in the underlying core-io library.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.6/com/couchbase/client/scala/index.html[API Reference]
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.6**
* com.couchbase.client:**core-io:2.2.6**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1060[JVMCBC-1060]:
Fixed an issue where rate limited exceptions were not thrown for `SearchIndexManager` errors.
* https://issues.couchbase.com/browse/JVMCBC-1071[JVMCBC-1071]:
The SDK now ensures that negative values are not sent to the `ValueRecorder`.

=== New Features
* https://issues.couchbase.com/browse/JVMCBC-1057[JVMCBC-1057]:
Added core infrastructure for the Backup service. 
Users can now make custom HTTP requests to the Backup service.
* https://issues.couchbase.com/browse/JVMCBC-1064[JVMCBC-1064]:
When implementing a custom `RetryStrategy`, a new overload of `RetryAction.noRetry` lets you specify an exception translator for converting the default request cancellation exception into your preferred exception class.

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1065[JVMCBC-1065]:
`RetryReason.allowsNonIdempotentRetry()` is now public, so you can call it from a custom `RetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-1066[JVMCBC-1066]:
When `SecurityConfig.Builder.trustCertificate(Path)` is given a file containing more than one certificate, it now trusts all the certificates instead of just the first one.
Likewise, the result of `SecurityConfig.decodeCertificates(List<String>)` now includes all certificates in each string, not just the first certificate in each string.
* https://issues.couchbase.com/browse/JVMCBC-1068[JVMCBC-1068]:
Added explicit handling of `FeatureNotAvailable` for Magma on CE.
* https://issues.couchbase.com/browse/JVMCBC-1069[JVMCBC-1069]:
Added explicit handling of `FeatureNotAvailable` for Query CE.

== Version 1.2.5 (2 February 2021)

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.5/com/couchbase/client/scala/index.html[API Reference]
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.5**
* com.couchbase.client:**core-io:2.2.5**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bugs
* https://issues.couchbase.com/browse/SCBC-339[SCBC-339]:
`QueryIndexManager` `watchIndexes` now refreshes on every try.
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Do not load global config if node not in seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1058[JVMCBC-1058]:
When a non-default scope or collection is being created with memcached buckets, the correct `FeatureNotAvailableException` is now thrown.

=== Improvements
* https://issues.couchbase.com/browse/SCBC-341[SCBC-341]:
Removed the Azure link type from the analytics management API, due to a change in the underlying server API.
(Note that this interface is marked `@Stability.Volatile`, indicating that it can change.)
* https://issues.couchbase.com/browse/SCBC-315[SCBC-315]:
Custom conflict resolution added to the bucket management API.
* https://issues.couchbase.com/browse/SCBC-319[SCBC-319]:
FTS options now include `IncludeLocations` and Operator.
* https://issues.couchbase.com/browse/SCBC-333[SCBC-333]:
Query API now supports preserving TTL.
* https://issues.couchbase.com/browse/SCBC-335[SCBC-335]:
Index management API now supports managing indexes for a collection.
* https://issues.couchbase.com/browse/SCBC-342[SCBC-342]:
Send configured user timeout to search.
* https://issues.couchbase.com/browse/JVMCBC-1037[JVMCBC-1037]:
Avoid `whenComplete` closure for timeout cancellation.
This is a small internal performance optimisation.
* https://issues.couchbase.com/browse/JVMCBC-1045[JVMCBC-1045]:
Added an internal watchdog that updates the cluster configuration if the number of nodes changes.
* https://issues.couchbase.com/browse/JVMCBC-1048[JVMCBC-1048]:
Always set `RequestContext` on `RequestSpan`.
* https://issues.couchbase.com/browse/JVMCBC-1056[JVMCBC-1056]:
Log more info on unexpected endpoint disconnect.
* https://issues.couchbase.com/browse/JVMCBC-1059[JVMCBC-1059]:
Handles any `retry:true` field in a query error result by retrying it.
* https://issues.couchbase.com/browse/JVMCBC-1055[JVMCBC-1055],
https://issues.couchbase.com/browse/JVMCBC-1047[JVMCBC-1047],
https://issues.couchbase.com/browse/JVMCBC-1051[JVMCBC-1051]:
Updating dependencies.
Netty goes from 4.1.72.Final to 4.1.73.Final.
Jackson from 2.13.0 to 2.13.1.
Reactor from 3.4.12 to 3.4.14.
log4j (an optional dependency) from 2.15.0 to 2.17.1.


== Version 1.2.4 (9 December 2021)
https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.4/com/couchbase/client/scala/index.html[API Reference]
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.4**
* com.couchbase.client:**core-io:2.2.4**
* io.projectreactor:**reactor-core:3.4.12**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/SCBC-334[SCBC-334]:
Bucket Management API - Added Storage Option for Magma.

* https://issues.couchbase.com/browse/JVMCBC-1033[JVMCBC-1033], https://issues.couchbase.com/browse/JVMCBC-1034[JVMCBC-1034]:
Updated internal and external dependencies to their latest bugfix versions.
Also updated OpenTelemetry to 1.7.x.

* https://issues.couchbase.com/browse/JVMCBC-1035[JVMCBC-1035]:
Made the (internal) subDocumentField is now serializable.
This is needed for Apache Spark integration.

* https://issues.couchbase.com/browse/JVMCBC-1032[JVMCBC-1032]:
Adde (volatile) support for Rate/Quota Limits.
This is needed for Couchbase Capella.

* https://issues.couchbase.com/browse/JVMCBC-1039[JVMCBC-1039]:
Included httpStatus in Query and Analytics Error Context, as well as the vbucket in the KV error context.
This helps with debugging.


== Version 1.2.3 (2 November 2021)

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.3/com/couchbase/client/scala/index.html[API Reference]
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.3**
* com.couchbase.client:**core-io:2.2.3**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1026[JVMCBC-1026]:
Added support for Error Map v2.

* https://issues.couchbase.com/browse/SCBC-326[SCBC-326]:
Added `LookupInResult.contentAsBytes()`.

* https://issues.couchbase.com/browse/SCBC-324[SCBC-324];
https://issues.couchbase.com/browse/SCBC-337[SCBC-337]
Updated dependencies.


== Version 1.2.2 (6 October 2021)

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.2/com/couchbase/client/scala/index.html[API Reference]
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.2**
* com.couchbase.client:**core-io:2.2.2**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/SCBC-265[SCBC-265]:
Added an eventing management API.
* https://issues.couchbase.com/browse/SCBC-332[SCBC-332]:
Fixes to `JsonObject` and `JsonArray`: improvements to the API for Safe transformations, `fromSeq`, fixed some conversion issues.
* https://issues.couchbase.com/browse/JVMCBC-1015[JVMCBC-1015]:
Improved client side error message when TLS is enforced on the server side.
* https://issues.couchbase.com/browse/JVMCBC-1016[JVMCBC-1016]:
Gracefully handle more invalid connection string cases.
* https://issues.couchbase.com/browse/JVMCBC-1022[JVMCBC-1022]:
Batch-Log messages in DefaultEventBus. Now events which
are overflowing are not directly logged to stderr but rather
batched up and logged at interval.
Note that this implies some "loss of precision", as
not all dropped events are logged - one event per type is preserved.

=== Interface Affecting
* https://issues.couchbase.com/browse/SCBC-331[SCBC-331]:
Promoted Manager interfaces to committed.

=== Bugs
* https://issues.couchbase.com/browse/SCBC-330[SCBC-330]:
Ensured that JsonObjectSafe is recursive.
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
Fixed issue with Threshold Logging Tracing not working due to RequestContext not being set.
* https://issues.couchbase.com/browse/JVMCBC-1020[JVMCBC-1020]:
Added `target` property to QueryRequest and ensured it is honored for prepare and execute, so they are both run on the same node. This fix removes need for `TargetedQueryRequest`.


== Version 1.2.1 (1 September 2021)

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.1/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.1**
* com.couchbase.client:**core-io:2.2.1**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/SCBC-328[SCBC-328]:
Update collections compat dependency.
* https://issues.couchbase.com/browse/SCBC-325[SCBC-325]:
Add serialization support for Apache Spark.
* https://issues.couchbase.com/browse/SCBC-329[SCBC-329]:
Expose all builder methods on SecurityConfig.
* https://issues.couchbase.com/browse/JVMCBC-1010[JVMCBC-1010]:
Maintenance dependency bump.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
WaitUntilReady timing out with 6.0.x and unhealthy seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.
* https://issues.couchbase.com/browse/JVMCBC-1004[JVMCBC-1004]:
Configure and apply default log level for ConsoleLogger.
* https://issues.couchbase.com/browse/JVMCBC-1005[JVMCBC-1005]:
Allow to export Context as Map.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
ErrorContext must be included in message.

=== Bug fixes
* https://issues.couchbase.com/browse/JVMCBC-1002[JVMCBC-1002]:
Default log level reverted to INFO.
* https://issues.couchbase.com/browse/JVMCBC-1007[JVMCBC-1007]:
LoggingMeter incorrectly marked as Volatile in SDK 3.2.


== Version 1.2.0 (20 July 2021)

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.2.0/com/couchbase/client/scala/index.html[API Reference]

Version 1.2.0 is the first GA release of the 1.2 series, promoting to GA support for the scopes and collections provided by Couchbase Server 7.0, and also OpenTelemetry.
In addition, a supported release for Scala 2.13 is now provided.

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.2.0**
* com.couchbase.client:**core-io:2.2.0**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvement
* https://issues.couchbase.com/browse/SCBC-217[SCBC-217]:
Provide a published and officially supported Scala 2.13 build.
* https://issues.couchbase.com/browse/SCBC-231[SCBC-231]:
Update analytics management API to support compound dataverse names.
* https://issues.couchbase.com/browse/SCBC-232[SCBC-232]:
Manage remote analytics links.
* https://issues.couchbase.com/browse/SCBC-240[SCBC-240]:
Add analytics support for collections.
* https://issues.couchbase.com/browse/SCBC-309[SCBC-309]:
Map Query Error 13014 to AuthenticationException.
* https://issues.couchbase.com/browse/SCBC-205[SCBC-205]:
Provide a Scala version of the Travel Sample Application backend.
* https://issues.couchbase.com/browse/JVMCBC-980[JVMCBC-980]:
Add exception wrappers to Tracers and Meters.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Map Query Error 13014 to AuthenticationException.
* https://issues.couchbase.com/browse/JVMCBC-989[JVMCBC-989]:
Add timeout_ms to threshold logging tracer output.
* https://issues.couchbase.com/browse/JVMCBC-991[JVMCBC-991]:
Optimize metric dispatching.
* https://issues.couchbase.com/browse/JVMCBC-992[JVMCBC-992]:
Cache NodeIdentifier in NodeInfo.
* https://issues.couchbase.com/browse/JVMCBC-993[JVMCBC-993]:
Optimize early discard of events which are not going to be logged.
* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw FeatureNotAvailableException if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-997[JVMCBC-997]:
Duplicate attributes from dispatch_to_server to improve tracing.
* https://issues.couchbase.com/browse/JVMCBC-998[JVMCBC-998]:
Performance: Do not set tracing spans if not needed.
* https://issues.couchbase.com/browse/JVMCBC-981[JVMCBC-981]:
Support CoreHttpClient requests to manager service.
* https://issues.couchbase.com/browse/JVMCBC-984[JVMCBC-984]:
Dependency bump: Netty 4.1.63 to 4.1.65, micrometer 1.6.6 to 1.7.0.
* https://issues.couchbase.com/browse/JCBC-1242[JCBC-1242],
https://issues.couchbase.com/browse/JCBC-1837[JCBC-1837]:
Add OSGi bundle.
* https://issues.couchbase.com/browse/JCBC-1787[JCBC-1787]:
Validate expiry instants.
* https://issues.couchbase.com/browse/JCBC-1838[JCBC-1838]:
Add support for SDK2-compatible LegacyTranscoder.
* https://issues.couchbase.com/browse/JCBC-1841[JCBC-1841]:
Update OpenTelemetry to 1.3.0.

=== Interface Changes
All interface changes are to interfaces that are currently in beta and marked @Stability.Volatile or @Stability.Uncommitted.

* https://issues.couchbase.com/browse/JVMCBC-978[JVMCBC-978]:
Rename AggregatingMeter to LoggingMeter.
* https://issues.couchbase.com/browse/JVMCBC-934[JVMCBC-934]:
Threshold and Orphan output is now in new format.
* https://issues.couchbase.com/browse/JVMCBC-979[JVMCBC-979]:
Rename ThresholdRequestTracer to ThresholdLoggingTracer
* https://issues.couchbase.com/browse/SCBC-297[SCBC-297]:
Promote collection APIs from Volatile to Committed.

=== Bug Fixes
* https://issues.couchbase.com/browse/SCBC-270[SCBC-270]:
Add redundant error handling for collection manager errors.
* https://issues.couchbase.com/browse/SCBC-296[SCBC-296]:
JsonArraySafe should create an object wrapping a JsonObject.
* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Ignore slow subscribers on certain Flux intervals.

== Version 1.1.8 (1 March 2022)
https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.8/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.8**
* com.couchbase.client:**core-io:2.1.8**
* io.projectreactor:**reactor-core:3.4.15**
* org.reactivestreams:**reactive-streams:1.0.3**

== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1067[JVMCBC-1067]:
Internal and external maintenance dependencies are updated to their latest available bugfix releases (including Netty to 4.1.74.Final).
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Added fix to not load the global config if a node is not in the seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
`ErrorContext` is now included in the message of a `CouchbaseException`.

== Version 1.1.7 (11 August 2021)
https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.7/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.7**
* com.couchbase.client:**core-io:2.1.7**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Slow subscribers are now ignored on certain Flux intervals.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
The SDK now gracefully handles cluster-level WaitUntilReady against clusters < 6.5.
* https://issues.couchbase.com/browse/SCBC-296[SCBC-296]:
Fixes a `JsonArraySafe` bug.

=== Improvements

* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw `FeatureNotAvailableException` if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Query error code 13014 is now mapped to `AuthenticationException`.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.


== Improvements

== Version 1.1.6 (4 June 2021)
https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.6/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.6**
* com.couchbase.client:**core-io:2.1.6**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-972[JVMCBC-972]:
Only open one GCCCP connection per node.

=== Improvements
* https://issues.couchbase.com/browse/SCBC-237[SCBC-237]:
Added `ThresholdRequestTracerConfig` and support for it in `ClusterEnvironment`.
* https://issues.couchbase.com/browse/SCBC-286[SCBC-286]:
Added `AggregatingMeterConfig`, and allow the core `meter` property to be customized via `ClusterEnvironment`.
* https://issues.couchbase.com/browse/JVMCBC-939[JVMCBC-939]:
Improve no collection access handling.
* https://issues.couchbase.com/browse/JVMCBC-974[JVMCBC-974]:
Restructure AggregatingMeter output format.
* https://issues.couchbase.com/browse/JVMCBC-975[JVMCBC-975]:
Further improve wait until ready diagnostics.
* https://issues.couchbase.com/browse/JVMCBC-977[JVMCBC-977]:
Improve bucket configuration handling (revEpoch).

== Version 1.1.5 (6 May 2021)
https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.5/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.5**
* com.couchbase.client:**core-io:2.1.5**
* io.projectreactor:**reactor-core:3.4.5**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/SCBC-266[SCBC-266]:
Add FTS support for collections.
* https://issues.couchbase.com/browse/SCBC-281[SCBC-281]:
Add Support to Preserve TTL.

== Version 1.1.4 (7 April 2021)

While there are no changes specific to the Scala SDK in this release, it does inherit fixes from the underlying core-io release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.4/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.4**
* com.couchbase.client:**core-io:2.1.4**
* io.projectreactor:**reactor-core:3.4.4**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1798[JCBC-1798]:
Fixes ViewResult.metaData() throwing Exception when debug=true.

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1786[JCBC-1786]:
Transcoders now allow contentAs(Object.class).
Java Map and List collections are used to represent JSON objects and arrays.
* https://issues.couchbase.com/browse/JCBC-1795[JCBC-1795]:
Allow `MutateInSpec.remove("")`, which removes the entire document.


== Version 1.1.3 (2 March 2021)

Version 1.1.3 is the fourth release of the 1.1 series, bringing stabilizations and enhancements over 1.1.2.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.3/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.3**
* com.couchbase.client:**core-io:2.1.3**
* io.projectreactor:**reactor-core:3.4.3**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements
* https://issues.couchbase.com/browse/SCBC-285[SCBC-285]:
Expose property loading on environment.
* https://issues.couchbase.com/browse/JVMCBC-924[JVMCBC-924],
https://issues.couchbase.com/browse/JVMCBC-925[JVMCBC-925]:
Updated dependencies: Netty to 4.1.59, netty-tcnative-boringssl-static to 2.0.36, Reactor to 2.4.3, Jackson to 2.12.1.
* https://issues.couchbase.com/browse/JVMCBC-919[JVMCBC-919]:
Support for Project Reactor BlockHound integration.
* https://issues.couchbase.com/browse/JVMCBC-926[JVMCBC-926]:
Performance: Replace new byte[] full copies with ByteBufUtil.getBytes.
* https://issues.couchbase.com/browse/JVMCBC-927[JVMCBC-927]:
Performance: Improve performance of metrics hot code path.

=== Bugs
* https://issues.couchbase.com/browse/JVMCBC-930[JVMCBC-930]:
Threshold and Orphan Reporting now report the correct time units.
* https://issues.couchbase.com/browse/JVMCBC-932[JVMCBC-932]:
Fixed a memory leak when OrphanReporter is disabled.
* https://issues.couchbase.com/browse/JVMCBC-933[JVMCBC-933]:
ThresholdRequestTracer and OrphanReporter now use bounded queues.

=== Internal Improvements
* https://issues.couchbase.com/browse/JVMCBC-912[JVMCBC-912]:
Refactor property loading.
* https://issues.couchbase.com/browse/JVMCBC-918[JVMCBC-918]:
Move ProjectionsApplier into core.
* https://issues.couchbase.com/browse/JVMCBC-920[JVMCBC-920]:
Move MutationState logic to core.
* https://issues.couchbase.com/browse/JVMCBC-921[JVMCBC-921]:
Add OpenTelemetry attributes for spans.
* https://issues.couchbase.com/browse/JVMCBC-929[JVMCBC-929]:
Retain stability annotations at runtime.
* https://issues.couchbase.com/browse/SCBC-284[SCBC-284]:
Expose package-level APIs for Spark interop.

== Version 1.1.2 (2 February 2020)

Version 1.1.2 is the third release of the 1.1 series, bringing stabilizations and enhancements over 1.1.1.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.2/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.2**
* com.couchbase.client:**core-io:2.1.2**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bugs
* https://issues.couchbase.com/browse/SCBC-282[SCBC-282]:
Collection map is no longer refreshed when using the default scope and default collection.

=== API Affecting
* https://issues.couchbase.com/browse/SCBC-288[SCBC-288]:
CollectionManager::getScope is now deprecated, in favour of using getAllScopes.

=== Enhancements
* https://issues.couchbase.com/browse/JVMCBC-915[JVMCBC-915]:
As a performance optimization, loading a collection now only fetches the information required for that collection, rather than the full collection manifest.
* https://issues.couchbase.com/browse/JVMCBC-916[JVMCBC-916]:
Any send HTTP request will send a hostname if hostnames are used, rather than IP, leading to consistent hostname use across the system.

== Version 1.1.1 (12 January 2020)
Version 1.1.1 is the second release of the 1.1 series, bringing stabilizations and enhancements over 1.1.

http://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.1/[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.1**
* com.couchbase.client:**core-io:2.1.1**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bugs
* https://issues.couchbase.com/browse/JVMCBC-909[JVMCBC-909]:
Retry opening the bucket until timeout when it is not found, to allow for it not yet being created.
* https://issues.couchbase.com/browse/JVMCBC-910[JVMCBC-910]:
WaitUntilReady will now wait if bucket not present yet, before it starts to time out.
* https://issues.couchbase.com/browse/SCBC-274[SCBC-274]:
Prepared non-adhoc queries on scopes were failing, as query_context was not being passed to the individual prepare and/or execute statements.
This has now been fixed, and scope-level queries are working as expected. 

=== Enhancements
* https://issues.couchbase.com/browse/SCBC-273[SCBC-273]:
Exposed partition information from the query management API on `QueryIndex` class.
* https://issues.couchbase.com/browse/SCBC-275[SCBC-275]:
Escape the scope for scope-level queries now enabled, as a fix in the server means that this works.

== Version 1.1.0 (2 December 2020)

Version 1.1.0 is the first GA release of the 1.1 series, bringing stabilizations and enhancements over 1.0.10 and the 1.0 SDK, and adding features to support Couchbase Server 6.6 and 7.0β.

http://docs.couchbase.com/sdk-api/couchbase-scala-client-1.1.0/[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.1.0**
* com.couchbase.client:**core-io:2.1.0**
* io.projectreactor:**reactor-core:3.4.0**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* https://issues.couchbase.com/browse/SCBC-241[SCBC-241]:
Refactored Document Expiry Duration.
* https://issues.couchbase.com/browse/SCBC-253[SCBC-253]:
Added disableScoring parameter for Search.
* https://issues.couchbase.com/browse/SCBC-229[SCBC-229]:
The minimum durability level can now be configured on the `BucketManager`.


== Version 1.0.10 (3 November 2020)

Version 1.0.10 is a maintenance release, bringing enhancements over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.10/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.10**
* com.couchbase.client:**core-io:2.0.11**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-898[JVMCBC-898]:
Added fallback for lastDispatchedTo in context, to improve debuggability.
* https://issues.couchbase.com/browse/JVMCBC-899[JVMCBC-899]:
Updated OpenTelemetry to 0.9.1.
* https://issues.couchbase.com/browse/SCBC-252[SCBC-252]:
Enhanced user management for collections/RBAC, to support future 7.0 release.




== Version 1.0.9 (7 October 2020)

Version 1.0.9 is a maintenance release, bringing enhancements and bugfixes over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.9/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.9**
* com.couchbase.client:**core-io:2.0.10**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**


=== Bug Fixes
* https://issues.couchbase.com/browse/SCBC-254[SCBC-254]: 
Fixed a decode error (allocstall) on BucketSettings with certain long values sent from particular server versions by swapping out upickle for JsonObject decoding.
* https://issues.couchbase.com/browse/SCBC-257[SCBC-257]: 
Fixed FTS serialization issues.
* https://issues.couchbase.com/browse/JVMCBC-885[JVMCBC-885]: 
Allow overriding of `BestEffortRetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-889[JVMCBC-889]: 
Make sure WaitUntilReady always times out.
* https://issues.couchbase.com/browse/JVMCBC-890[JVMCBC-890]: 
Enforce only negotiate PLAIN when using TLS with PasswordAuthenticator.
* https://issues.couchbase.com/browse/JVMCBC-892[JVMCBC-892]: 
Service pool idle time check now happen more often.
* https://issues.couchbase.com/browse/JVMCBC-894[JVMCBC-894]: 
BatchHelper: handle success case with no body gracefully.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]: 
Subdoc 'no access' error code is now reported correctly.
This helps users to identify and fix permissions errors for system XATTRs.

=== Enhancements
* https://issues.couchbase.com/browse/SCBC-233[SCBC-233]: 
Geopolygon search support.
* https://issues.couchbase.com/browse/SCBC-234[SCBC-234]: 
Added support for FTS hints (flex index).
* https://issues.couchbase.com/browse/SCBC-236[SCBC-236]: 
Added ephemeral bucket management support.
* https://issues.couchbase.com/browse/SCBC-238[SCBC-238]: 
Added N1QL support for collections, via new `Scope.query` method.
* https://issues.couchbase.com/browse/SCBC-249[SCBC-249]: 
Added GetResult.expiryTime(), which returns an Instant vs GetResult.expiry()'s Duration.
* https://issues.couchbase.com/browse/JVMCBC-888[JVMCBC-888], 
https://issues.couchbase.com/browse/JVMCBC-893[JVMCBC-893]: 
Dependency bumps: Netty to 4.1.52.Final, OpenTelemetry to 0.8.
* https://issues.couchbase.com/browse/JVMCBC-886[JVMCBC-886]: 
Improved LDAP auth failure handling.
* https://issues.couchbase.com/browse/JVMCBC-896[JVMCBC-896]: 
Fast dispatch pooled requests.


== Version 1.0.8 (1 September 2020)

Version 1.0.8 is the ninth release of the Scala SDK, bringing enhancements and bugfixes over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.8/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.8**
* com.couchbase.client:**core-io:2.0.9**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
The client now handles bootstrapping against nodes much better which do not have the data service enabled (in an MDS setup).
* https://issues.couchbase.com/browse/JVMCBC-882[JVMCBC-882]:
A bug has been fixed where when bootstrapping against a node with no data service enabled, the endpoint would not be cleaned up and would keep trying to reconnect.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]:
The client now more explicitly handles an error response code (`NO_ACCESS`) when a subdocument request is performed against a system xattr.
* https://issues.couchbase.com/browse/JVMCBC-873[JVMCBC-873]:
Durability information is now properly unwrapped from an optional when exported and dumped (for example as part of an exception).
* https://issues.couchbase.com/browse/JVMCBC-880[JVMCBC-880]:
The client now trackes multiple parallel bucket open attempts (against different buckets) in a better way, making sure that an internal state is only switched when all those bucket open attempts have completed (and not just the first one).
* https://issues.couchbase.com/browse/JVMCBC-878[JVMCBC-878]:
`EndpointDiagnostics` had the local and remote hostnames mixed up, they now show up in the correct order.

=== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-883[JVMCBC-883]:
The client is now a little less verbose when performing a DNS SRV request and the underlying JDK operation times out.
* https://issues.couchbase.com/browse/JVMCBC-879[JVMCBC-879]:
Updated internal and external dependencies to their latest maintenance releases.
* https://issues.couchbase.com/browse/JVMCBC-874[JVMCBC-874]:
When dealing with unknown collections, the SDK now returns a more user friendly retry reason when it can (outdated manifest vs. collection not found).
* https://issues.couchbase.com/browse/JVMCBC-875[JVMCBC-875]:
On the request timeout exception, the retry reasons are now accessible directly.


== Version 1.0.7 (4 August 2020)

Version 1.0.7 is the eighth release of the Scala SDK, bringing enhancements, and bugfixes over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.7/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.7**
* com.couchbase.client:**core-io:2.0.8**
* io.projectreactor:**reactor-core:3.3.8.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes
* https://issues.couchbase.com/browse/SCBC-247[SCBC-247]: 
Removed cas from `IncrementOptions` and `DecrementOptions`.  
CAS is not supported by the underlying protocol and should not have been exposed in these options.
* https://issues.couchbase.com/browse/JVMCBC-870[JVMCBC-870]: 
A bug in the chunk response parser prohibited responses meant that View reduce responses were never completed, and as a result timed out on the user side.
The completion of view results with reduce enabled has now been fixed.

=== Enhancements
* https://issues.couchbase.com/browse/JVMCBC-867[JVMCBC-867]: 
Performance improvement: do not grab ByteBuf slice when extracting server response time.
* https://issues.couchbase.com/browse/JVMCBC-869[JVMCBC-869]: 
Maintenance dependency bump: Netty -> 4.1.51, Jackson -> 2.11.1, Reactor -> 3.3.7, OpenTelemetry -> 0.6.0, Reactor Scala Extensions -> 0.7.1.


== Version 1.0.6 (14 July 2020)

Version 1.0.6 is the seventh release of the Scala SDK.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.6/com/couchbase/client/scala/index.html[API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.6**
* com.couchbase.client:**core-io:2.0.7**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements
* https://issues.couchbase.com/browse/JVMCBC-865[JVMCBC-865]:
Change the default idle timeout to 4.5s for http connections, to support performance improvements in query service.

=== Bug Fixes
* https://issues.couchbase.com/browse/SCBC-244[SCBC-244]:
ViewQuery with keys does not work.
* https://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Redundant global loading exceptions no longer propagated -- now logged at `debug` level.
* https://issues.couchbase.com/browse/JVMCBC-856[JVMCBC-856]:
A just-opened connection in pool no longer gets cleaned up prematurely .
* https://issues.couchbase.com/browse/JVMCBC-858[JVMCBC-858]:
Channel writeAndFlush failures are no longer ignored.
* https://issues.couchbase.com/browse/JVMCBC-862[JVMCBC-862]:
Race condition with node identifier change on bootstrap identified.
New logic and some changes to the config provider code ensures that retry and resubscribe picks up fresh seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-863[JVMCBC-863]:
Bucket-Level ping report no longer includes other view and KV services buckets.
* https://issues.couchbase.com/browse/JVMCBC-866[JVMCBC-866]:
Trailing : no longer added to IPv6 addresses without [].
'invalid IPv6 address' warnings now no longer produced when trying to connect to a valid Ipv6 address thus specified.

== Version 1.0.5 (2 June 2020)

Version 1.0.5 is the sixth release of the Scala SDK.
It brings no new changes to the Scala client itself, but inherits enhancements and bugfixes over the last stable release from the core-io dependency.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.5/com/couchbase/client/scala/index.html[API Reference] 
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.5**
* com.couchbase.client:**core-io:2.0.6**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-852[JVMCBC-852]:
Bumped Reactor to 3.3.5, Netty to 4.1.50.Final, and Jackson to 2.11.0.
* https://issues.couchbase.com/browse/JVMCBC-693[JVMCBC-693]:
For performance, the KV bootstrap sequence is now partially pipelined.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Duplicate global loading exceptions are now swallowed to remove redundant warnings from logging (this was a cosmetic-only issue).


== Version 1.0.4 (7 May 2020)

Version 1.0.4 is the fifth release of the Scala SDK.
It brings no new changes to the Scala client itself, but inherits enhancements and bugfixes over the last stable release from the core-io dependency.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.4/com/couchbase/client/scala/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.4**
* com.couchbase.client:**core-io:2.0.5**
* io.projectreactor:**reactor-core:3.3.4.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-841[JVMCBC-841]:
Bumped Netty dependency to 2.0.30, and reactor to 3.3.4.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-845[JVMCBC-845]:
If a rebalance is stopped in the middle, an edge case occasionally causes KV ops to time out as the fast forward map is chosen over the retry.
The behavior has now been changed so that the client will try the old and new servers to make sure the operation eventually gets dispatched to the right node.

== Version 1.0.3 (7 April 2020)

Version 1.0.3 is the fourth release of the Scala SDK.
It brings no new changes to the Scala client itself, but inherits enhancements and bugfixes over the last stable release from the core-io dependency.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.3/com/couchbase/client/scala/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.3**
* com.couchbase.client:**core-io:2.0.4**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-830[JVMCBC-830]:
Added more convenient overloads for SecurityConfig and CertAuth. 
These overloads initialize both the SecurityConfig and the CertificateAuthenticator directly from a KeyStore or TrustStore. 
* http://issues.couchbase.com/browse/JVMCBC-831[JVMCBC-831]:
Improves timeout for waitUntilReady -- the `waitUntilReady` helper should now throw a proper timeout exception. 
* http://issues.couchbase.com/browse/JVMCBC-832[JVMCBC-832]:
Added support for multiple ports per hostname in the connection string -- without having to use the explicit SeedNode set overload.
* http://issues.couchbase.com/browse/JVMCBC-835[JVMCBC-835]:
Using "localhost:8091" as a connection string would set the kv bootstrap port to 8091, which is not desired behavior.
To prevent this from happening again, the code now checks for this condition, fails fast, and also provides guidance on what the connection string should look like instead.
* http://issues.couchbase.com/browse/JVMCBC-836[JVMCBC-836]:
Enabled Unordered Execution by Default.
* http://issues.couchbase.com/browse/JVMCBC-837[JVMCBC-837]:
Updates OpenTelemetry to 0.3 (beta).
* http://issues.couchbase.com/browse/JVMCBC-839[JVMCBC-839]:
Bootstrap will now correctly use the mapped port if alternate addr is present.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-834[JVMCBC-834]:
'CollectionNotFoundException' now triggers a retry, and if no collection refresh is currently in progress it will proactively trigger a new one.
Now Docs created under custom collection should no longer raise an exception when a collection has been created in the meantime, but the collection is not found as no refresh is in progress.
* http://issues.couchbase.com/browse/JVMCBC-826[JVMCBC-826]:
A NullPointerException was occuring when LDAP is enabled.
The code now explicitly fails the connection with a descriptive error message instructing the user what to do next (either use TLS which is preferred) or enable PLAIN on the password authenticator (insecure).
* http://issues.couchbase.com/browse/JVMCBC-827[JVMCBC-827]:
Search query results row_hit typo resulted in 0 being returned for total rows. 
This has now been fixed. 
* http://issues.couchbase.com/browse/JVMCBC-828[JVMCBC-828]:
Omit internal config request in orphan reporting.

== Version 1.0.2 (3 March 2020)

Version 1.0.2 is the third release of the Scala SDK, bringing enhancements and bugfixes over the last stable release.

https://docs.couchbase.com/sdk-api/couchbase-scala-client-1.0.2/scaladocs/com/couchbase/client/scala/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**scala-client:1.0.2**
* com.couchbase.client:**core-io:2.0.3**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-813[JVMCBC-813]:
Improved error message for bucket is missing.
* http://issues.couchbase.com/browse/JVMCBC-815[JVMCBC-815]:
Check if key exceeds size limits.
* http://issues.couchbase.com/browse/JVMCBC-818[JVMCBC-818]:
Trimmed netty stack in connect failures for more readable output.
* http://issues.couchbase.com/browse/JVMCBC-819[JVMCBC-819]:
Distinguished bucket not found in select bucket failures.
* http://issues.couchbase.com/browse/JVMCBC-823[JVMCBC-823]:
Added a global component to the core id.
* http://issues.couchbase.com/browse/JVMCBC-825[JVMCBC-825]:
Support added for new VATTR HELLO flag.
* http://issues.couchbase.com/browse/SCBC-43[SCBC-43]:
With huge thanks to our community, who submitted the patch, it is now possible to build versions of the SDK for 2.11 and 2.13.
Couchbase only officially provides, tests and supports a Scala 2.12 build currently, but users are welcome to build their own jars for 2.11 or 2.13 following the https://github.com/couchbase/couchbase-jvm-clients[README instructions].

=== Bug Fixes

* http://issues.couchbase.com/browse/SCBC-200[SCBC-200]:
Dependencies now correctly shaded.
* http://issues.couchbase.com/browse/SCBC-207[SCBC-207]:
Exists no longer returns wrong value if executed right after remove.
* http://issues.couchbase.com/browse/SCBC-216[SCBC-216]:
Properly clear cache when repreparing/retrying query.
* http://issues.couchbase.com/browse/JVMCBC-824[JVMCBC-824]:
Native Netty transports not included, resulting in fallback to default implementation.  This was a regression in the 2.0.2 core-io release.
* http://issues.couchbase.com/browse/JCBC-1600[JCBC-1600]:
Using expiry together with document flags on a Sub-Document `mutateIn` no longer causes an incorrect flags field to be sent.

== Version 1.0.1 (5th February 2020)

Version 1.0.1 is the second release of the 1.0 series, bringing new features, enhancements, and bugfixes over the last stable release.

=== Stability Enhancements & Bug Fixes
* https://issues.couchbase.com/browse/SCBC-192[SCBC-192]:
All scaladoc warnings fixed.
* https://issues.couchbase.com/browse/SCBC-193[SCBC-193]:
When creating buckets, numReplicas can now be specified.

=== New Features & Enhancements
* https://issues.couchbase.com/browse/SCBC-190[SCBC-190]:
Exposed enableDnsSrv parameter on `IoConfig()`, allowing DNS SRV to be used.
* https://issues.couchbase.com/browse/SCBC-204[SCBC-204]:
Added support for new server flag `createAsDeleted` -- for internal use only.
* https://issues.couchbase.com/browse/SCBC-201[SCBC-201]:
Exposed Java core environment through Scala ClusterEnvironment, allowing the event-bus to be accessed.
* https://issues.couchbase.com/browse/SCBC-198[SCBC-198]:
Exposed environment getter through cluster. 
This allows a constructed environment to be shutdown without having to maintain a reference to it.

== Version 1.0.0 (17th January 2020)

This is the first General Availability (GA) release of the new Couchbase Scala SDK.
It brings a large number of improvements, bug-fixes and API changes from the previous beta release.

=== Stability Enhancements & Bug Fixes
* https://issues.couchbase.com/browse/SCBC-147[SCBC-147]:
QueryIndexManager should return only GSI indexes
* https://issues.couchbase.com/browse/SCBC-151[SCBC-151]:
Make sure all reactive ops are deferred; this ensures that `collection.reactive.remove(...)` won't perform a remove until the SMono is subscribed to
* https://issues.couchbase.com/browse/SCBC-154[SCBC-154]:
Make UserManager handle pre-LDAP clusters
* https://issues.couchbase.com/browse/SCBC-157[SCBC-157]:
Handle projections of objects inside arrays correctly
* https://issues.couchbase.com/browse/SCBC-158[SCBC-158]:
Handle 'too many set inserts' internal error while converting JSON to case classes
* https://issues.couchbase.com/browse/SCBC-163[SCBC-163]:
ViewQuery does not send request
* https://issues.couchbase.com/browse/SCBC-167[SCBC-167]:
Fix FTS consistentWith
* https://issues.couchbase.com/browse/SCBC-174[SCBC-174]:
ReactiveCollection KV operations now do ClientVerified Observe check
* https://issues.couchbase.com/browse/SCBC-182[SCBC-182]:
QueryOptions missing setters

=== New Features & Enhancements
* https://issues.couchbase.com/browse/SCBC-190[SCBC-190]:
Expose enableDnsSrv parameter on `IoConfig()`, allowing DNS SRV to be used
* https://issues.couchbase.com/browse/SCBC-192[SCBC-192]:
All scaladoc warnings fixed
* https://issues.couchbase.com/browse/SCBC-204[SCBC-204]:
Add support for new server flag `createAsDeleted`, for internal use only

=== API Changes
* https://issues.couchbase.com/browse/SCBC-159[SCBC-159]:
Fix semantics of datastructures so they behave more like Scala collections
* https://issues.couchbase.com/browse/SCBC-162[SCBC-162]:
All ReactiveBinaryCollection methods should return SMono
* https://issues.couchbase.com/browse/SCBC-164[SCBC-164]:
Align with latest view RFC
* https://issues.couchbase.com/browse/SCBC-136[SCBC-136]:
Track all Java environment changes
* https://issues.couchbase.com/browse/SCBC-138[SCBC-138]:
Replace management API Scala exceptions with core ones
* https://issues.couchbase.com/browse/SCBC-139[SCBC-139]:
GetSelecter is using incorrect exceptions
* https://issues.couchbase.com/browse/SCBC-155[SCBC-155]:
Rename *master to *active throughout
* https://issues.couchbase.com/browse/SCBC-187[SCBC-187]:
Remove scopeExists and collectionExists from CollectionManager
* https://issues.couchbase.com/browse/SCBC-188[SCBC-188]:
Align UserAndMetadata with latest RFC


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 1.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].
// enc::all[]
