= Best Practices
:description: Speed up your application development, with some best practices for using Couchbase SDKs.
:page-aliases: concept-docs:errors.adoc,concept-docs:rbac.adoc



// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}


// see .NET doc on this


From batching and reactive APIs, to unit tests and handling errors.
There's plenty that can be done to remove bottlenecks in development and in performance, and this page can be your checklist of areas not to neglect as you develop your app.



== Security

But before worrying about bottlenecks, let's put security concerns first.

Security is a process, and not just a set of checkboxes -- but 
//

=== Roles and RBAC

Self-managed Couchbase Server uses Role-Based Access Control (RBAC), which is reflected in our managed service as a nuanced set of Roles.
Data security depends in part on only giving access to 
// 



// concept snippet

include::{version-common}@sdk:pages:partial$rbac.adoc[]




== Performance

=== Dealing with Timeout Errors


// see also
// https://couchbasecloud.atlassian.net/wiki/spaces/CST/pages/1993769712/Java+-+Debugging+KV+Timeouts
// in Support wiki


* waitUntilReady
* WAN development





=== Read From Replica

Advanced zone aware....




=== Concurrency and Async APIs


....this paragraph different for each SDK.


== Error Handling

Errors


== Testing


.

== General Approach to Scala Exceptions

 When the unexpected happens, take a step-by-step approach.

include::{version-common}@sdk:shared:partial$errors.adoc[tag=exception]

// include::{version-common}@sdk:shared:partial$errors.adoc[tag=ref]

include::{version-common}@sdk:shared:partial$errors.adoc[tag=durability]

include::{version-common}@sdk:shared:partial$errors.adoc[tag=diag]

// Slow Operations Logging
include::{version-common}@sdk:shared:partial$errors.adoc[tag=observability]

// until opentelemetry release for link below, could add note on API to expose own tracing features?
// include::{version-common}@sdk:shared:partial$errors.adoc[tag=rto]





// Missing APIs
// For anything that is not covered by the SDK, 
// for example
// a raw FTS query from the SDK...
// use the HTTP client: 

////
public class CouchbaseHttpClient
extends Object
A specialized HTTP client for making requests to Couchbase Server.
Get an instance by calling Cluster.httpClient().

Example usage:

 public static String getAutoFailoverSettings(Cluster cluster) {
   HttpResponse response = cluster.httpClient().get(
       HttpTarget.manager(),
       HttpPath.of("/settings/autoFailover"));

   if (!response.success()) {
     throw new RuntimeException(
         "Failed to get auto-failover settings. HTTP status code " +
             response.statusCode() + "; " + response.contentAsString());
   }

   return response.contentAsString();
 }

 public static void disableAutoFailover(Cluster cluster) {
   HttpResponse response = cluster.httpClient().post(
       HttpTarget.manager(),
       HttpPath.of("/settings/autoFailover"),
       HttpPostOptions.httpPostOptions()
           .body(HttpBody.form(Map.of("enabled", "false"))));

   if (!response.success()) {
     throw new RuntimeException(
         "Failed to disable auto-failover. HTTP status code " +
             response.statusCode() + "; " + response.contentAsString());
   }
 }
 
////
// https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/http/CouchbaseHttpClient.html





// other SDK's docs
//
// add in Python
// https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/parallelism.html
//
// 