= Document 
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
//:page-aliases: ROOT:core-operations
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::6.5@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,python]
----
upsert(docid, document)
insert(docid, document)
replace(docid, document)
get(docid)
remove(docid)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::6.5@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[Sub-Document] operations which operate on specific subsets of documents:

[source,scala]
----
include::1.0@scala-sdk:howtos:example$SubDocument.scala[tag=upsert,indent=0]
----

or xref:6.0@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `default` SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::6.5@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM default USE KEYS ["docid"];
----

or

[source,sql]
----
SELECT * FROM default WHERE META(default).id = "docid";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[Sub-Document operations], by specifying one or more sections of the document to be retrieved

[source,scala]
----
include::1.0@scala-sdk:howtos:example$SubDocument.scala[tag=combine,indent=0]
----

// Counters

include::6.5@sdk:shared:partial$documents.adoc[tag=counters1]

[source,java]
----
//  java example:
String counterDocId = "counter-doc";
// Increment by 1, creating doc if needed
collection.binary().increment(counterDocId);
// Decrement by 1
collection.binary().decrement(counterDocId);
// Decrement by 5
collection.binary().decrement(counterDocId,
DecrementOptions.decrementOptions().delta(5));
----

include::6.5@sdk:shared:partial$documents.adoc[tag=counters2]

[source,python]
----
# Python example:
rv = cb.get('counter_id')
value, cas = rv.value, rv.cas
if should_increment_value(value):
  cb.upsert('counter_id', value + increment_amount, cas=cas)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`. 
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/AsyncBinaryCollection.html[in the API docs].

// Expiry
include::6.5@sdk:shared:partial$documents.adoc[tag=expiration]
