= Managing Couchbase Clusters from the SDK
:page-aliases: buckets-and-clusters.adoc
:description: Cluster management from the SDK.



[abstract]
{description}


The Couchbase {name-sdk} has a management API to provision clusters.
This is not the only programmatic way to deploy Couchbase, and you may wish to look at
xref:cloud:terraform:index.adoc[Terraform] for Capella, or some of our command line tools.


== buckets and clusters
////
= Buckets and Clusters
:description: The Couchbase Scala SDK provides an API for managing a Couchbase cluster programmatically.
:page-topic-type: concept
:page-aliases: managing-clusters

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

include::{version-common}@sdk:shared:partial$clusters-buckets.adoc[tag=management]

// ...
Management operations in the Scala SDK may be performed through several interfaces depending on the object:

== Creating and Removing Buckets

To create or delete a bucket, call the bucket manager with the `buckets()` call on the cluster:

[source,java]
----
Cluster cluster = Cluster.connect("127.0.0.1", "user", "123456");
BucketManager manager = cluster.buckets();
manager.createBucket(bucketSettings);
----

// The `BucketSettings` can be created via a builder, [.api]`DefaultBucketSettings.builder()`.
This class is also used to expose information about an existing bucket (`manager.getBucket(string)`) or to update an existing bucket (`manager.updateBucket(bucketSettings)`).

The default Collection & Default Scope will be used automatically.
////





// Collections & Scopes
////

The Collections feature in Couchbase Server 7.0 is fully implemented in the Scala SDK version 1.2.

Please see the xref:{version-server}@server:learn:data/scopes-and-collections.adoc[Scopes and Collections page] in the Server docs.

== Using Collections & Scopes

Access a non-default collection, in the default scope, with:

[source,scala]
----
include::example$CollectionsExample.scala[tag=collections_1,indent=0]
----

And for a non-default scope:
[source,scala]
----
include::example$CollectionsExample.scala[tag=collections_2,indent=0]
----


== Further Reading

To see Collections in action, take a look at our xref:howtos:working-with-collections.adoc[Collections-enabled Travel Sample page].
////

