= Querying with N1QL
:nav-title: Querying with N1QL
:page-topic-type: concept
:page-aliases: ROOT:n1ql-query,

[abstract]
Parallel data management for complex queries over many records, using a familiar SQL-like syntax.

include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=intro]


// Prepared Statements for Query Optimization
include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=prepared]

For the Scala SDK, the `adhoc` parameter should be set to `false` for a plan to be prepared, or a prepared plan to be reused.
Do not turn off the `adhoc` flag for _every_ query to Server 6.0 and earlier, since only a finite number of query plans (currently 5000) can be stored in the SDK.

[source,scala]
----
val result = cluster.query(
"select `travel-sample`.* from `travel-sample` limit 10;",
QueryOptions().adhoc(false)
)
----


== Indexes

The Couchbase query service makes use of xref:6.5@server:learn:services-and-indexes/indexes/indexes.adoc[_indexes_] in order to do its work.
Indexes replicate subsets of documents from data nodes over to index nodes, 
allowing specific data (for example, specific document properties) to be retrieved quickly, 
and to distribute load away from data nodes in xref:6.5@server:learn:services-and-indexes/services/services.adoc[MDS] topologies.

[IMPORTANT]
In order to make a bucket queryable, it must have at least one index defined.

You can define a _primary index_ on a bucket.
When a _primary_ index is defined you can issue non-covered (see below) queries on the bucket as well.
This includes using the `META` function in the queries.

[source,n1ql]
----
CREATE PRIMARY INDEX ON `users`
----

You can also define indexes over given document fields and then use those fields in the query:

[source,n1ql]
----
CREATE INDEX ix_name ON `users`(name);
CREATE INDEX ix_email ON `users`(email);
----

This would allow you to query the _users_ bucket regarding a document's `name` or `email` properties, thus:

[source,n1ql]
----
SELECT name, email FROM `users` WHERE name="Monty Python" OR email="monty@python.org";
----

Indexes help improve the performance of a query.
When an index includes the actual values of all the fields specified in the query, 
the index _covers_ the query, and eliminates the need to fetch the actual values from the Data Service.
An index, in this case, is called a _covering index_, and the query is called a _covered_ query.
For more information, see xref:6.5@server:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes].

You can also create and define indexes in the SDK using:

[source,scala]
----
include::example$N1qlQuery.scala[tag=create-index,indent=0]
----

== Index Building

Creating indexes on buckets with many existing documents can take a long time.
You can build indexes in the background, creating _deferred_ indexes.
The deferred indexes can be built together, rather than having to re-scan the entire bucket for each index.

[source,sql]
----
CREATE PRIMARY INDEX ON `users` WITH {"defer_build": true};
CREATE INDEX ix_name ON `users`(name) WITH {"defer_build": true};
CREATE INDEX ix_email ON `users`(email) WITH {"defer_build": true};
BUILD INDEX ON `users`(`#primary`, `ix_name`, `ix_email`);
----

The indexes are not built until the `BUILD INDEX` statement is executed.
At this point, the server scans all of the documents in the `users` bucket, 
and indexes it for all of the applicable indexes (in this case, those that have a `name` or `email` field).

Building deferred indexes can also be done via the SDK:

[source,scala]
----
include::example$N1qlQuery.scala[tag=build-index,indent=0]
----

Note that the build step is still asynchronous, so `watchIndexes` is used to wait for the indexes to be completed.
"#primary" is the primary index.


// Index Consistency
include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=index-consistency]

The following options are available:

include::6.5@server:learn:page$services-and-indexes/indexes/index-replication.adoc[tag=scan_consistency]

* A N1QL query using the default `NotBounded` scan consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

* With scan consistency set to `RequestPlus`, all outstanding document changes and index updates are processed before the query is run.
Select this when consistency is always more important than performance.

* For a middle ground, `AtPlus` is a "read your own write" (RYOW) option, which means it just waits for the documents that you specify to be indexed.

For N1QL, the default consistency is `not_bounded`.

Here's how to specify the `RequestPlus` scan consistency level:

[source,scala]
----
include::howtos:example$Queries.scala[tag=request-plus,indent=0]
----

And the `AtPlus` level is represented with `QueryScanConsistency.ConsistentWith`:

[source,scala]
----
include::howtos:example$Queries.scala[tag=at-plus,indent=0]
----
