= Start Using the Scala SDK
:page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc
:page-toclevels: 2
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}


Couchbase has a simple interface to create and modify records in a document, based upon the _Collection_ into which the documents are organised.
You can read more about data modelling <<data-modeling,below>>, but first let's look at those data operations, and installing the {name-sdk}.

// remember to add a nomenclature note to the next version of this page for LCB.

.Upsert with a Unique ID
[source,scala]
----
val docId = UUID.randomUUID().toString
collection.upsert(docId, json) match {
  case Success(result)    =>
  case Failure(exception) => println("Error: " + exception)
}
----

We'll explore creating and retrieving data records in more detail <<create-read-update-delete,below>>, after walking through a quick installation.


== Before You Start

Couchbase Capella, our Database-as-a-Service, lets you get on with what matters, whilst we take care of the administration for you.
Alternately, if you need to control every aspect of deployment -- or just want to run the Server in a VM on your laptop -- there are several self-managed options available:

[{tabs}]
==== 
Couchbase Capella::
+
--
If you haven't already got a database set up, the easiest route is to https://cloud.couchbase.com/sign-up[sign up to a trial of Couchbase Capella], then come back to this page.
Make a note of the xref:[endpoint] to connect to, and remember the credentials for the user that you set up.
--

Self-Managed Couchbase Server Options::
+
--
Alternatively, you may want to look at one of the self-managed installation options:

* xref:server:install:get-started.adoc[Deployment overview]
* xref:server:install:getting-started-docker.adoc[Docker Install]
* xref:operator::overview.adoc[Couchbase Autonomous Operator]
** xref:operator::install-kubernetes.adoc[Kubernetes]
** xref:operator::install-openshiftadoc[Openshift]
* xref:server:cloud:couchbase-cloud-deployment.adoc[Cloud Marketplace]:
** xref:server:cloud:couchbase-aws-marketplace.adoc[AWS Marketplace]
** xref:server:cloud:couchbase-azure-marketplace.adoc[Azure Marketplace]
** xref:server:cloud:couchbase-gcp-cloud-launcher.adoc[GCP Marketplace]
--
====


// Script the docs!
// Can any of the SDK installations be scripted?

=== Prerequisites

The Scala SDK is tested against LTS versions of Oracle JDK and OpenJDK -- see our xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].

The Couchbase {name-sdk} {sdk_dot_minor} Client supports Scala 2.12 and 2.13.


== Installation

More details of the installation proces can be found in the xref:project-docs:sdk-full-installation.adoc[full installation guide].
In most cases, given the above prerequisites, it's a simple matter of the following for your favorite build tool:

[{tabs}] 
==== 
SBT::
+
--
[source,sbt]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.5.1"
----

This will automatically use the Scala 2.12 or 2.13 builds, as appropriate for your SBT project.
--

Gradle::
+
--
It can be included in your `build.gradle` like this for 2.13:

[source,groovy]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.13', version: '1.5.1'
}
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--

Maven::
+
--
It can be included in your Maven `pom.xml` like this for 2.13:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.13</artifactId>
        <version>1.5.1</version>
    </dependency>
</dependencies>
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--
====


=== IDE Plugins

To make development easier, Couchbase plugins are available for VSCode and the IntelliJ family of IDEs and editors.
For links and more information on these and other integrations across the {name_platform} ecosystem, check out the xref:project-docs:third-party-integrations.adoc[] page.



== Connect to your Database

Connect to your Couchbase Capella database (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[{tabs}] 
==== 
Couchbase Capella::
+
--
[source,scala]
----
// Update this to your cluster
val endpoint = "cb.<your-endpoint>.cloud.couchbase.com"
val username = "username"
val password = "Password!123"
val bucketName = "travel-sample"

val env = ClusterEnvironment.builder
  .securityConfig(
    SecurityConfig()
      .enableTls(true)
  )
  // Sets a pre-configured profile called "wan-development" to help avoid latency issues
  // when accessing Capella from a different Wide Area Network
  // or Availability Zone (e.g. your laptop).
  .applyProfile(ClusterEnvironment.WanDevelopmentProfile)
  .build
  .get

val cluster = Cluster
  .connect(
    "couchbases://" + endpoint,
    ClusterOptions
      .create(username, password)
      .environment(env)
  )
  .get
----

Note, the client certificate for connecting to a Capella database is included in the SDK installation.
--

Self-Managed Couchbase::
+ 
-- 
[source,scala]
----
// Update this to your cluster
val username = "Administrator"
val password = "password"
val bucketName = "travel-sample"

val env = ClusterEnvironment.builder
  // You should uncomment this if running in a production environment.
  // .securityConfig(
  //   SecurityConfig()
  //     .enableTls(true)
  // )
  .build
  .get

val cluster = Cluster
  .connect(
    // For a secure cluster connection, use `couchbases://<your-cluster-ip>` instead.
    "couchbase://localhost",
    ClusterOptions
      .create(username, password)
      .environment(env)
  )
  .get
----
--
====

A deeper look at connection options can be found in xref:howtos:managing-connections.adoc[].

TIP: The connection code for getting started uses the Administrator password that you were given during set up.
In any production app you should create a role restricted to the permissions needed for your app -- more on this in xref:concept-docs:best-practices.adoc#roles-and-rbac[the Security documentation].

== Create, Read, Update, Delete

Couchbase documents are organized into buckets, scopes, and collections.
https://en.wikipedia.org/wiki/CRUD[CRUD operations^] -- Create, Read, Update, Delete -- can be performed upon documents in a collection.

[source,scala]
----

----






== Data Modeling

Documents are organized into collections -- collections of documents that belong together.. 
You get to decide what it means to "belong." 
Developers usually put documents of the same type in the same collection.

For example, imagine you have two types of documents: customers and invoices. 
You could put the customer documents in a collection called customers`, and the invoice documents in a collection called `invoices`.

Each document belongs to exactly one collection. 
A document’s ID is unique _within_ the collection.

Different scopes can hold collections with different names. 
There is no relationship between collections in different scopes.

Each collection belongs to exactly one scope. 
A collection’s name is unique within the scope.


More details can be found on the xref:concept-docs.data-model.adoc[Data Model page].


== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////



=== Help and Troubleshooting

* Forum
* Discord
* Read the xref:[error handling page].




=== Next Steps

* Take a look at the xref:hello-world:sample-application.adoc[].
* Explore some of the xref:project-docs:third-party-integrations.adoc[third party integrations] with Couchbase and the {name_platform} SDK, across the {name_platform} ecosystem.
























== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Scala SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
[source,scala]
----
include::example$Cloud.scala[tags=**]
----
--

Local Couchbase Server::
+
--
[source,scala]
----
include::example$StartUsing.scala[tags=**]
----
--
====

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.

== Quick Install

A more detailed guide in our xref:project-docs:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}] 
==== 
SBT::
+
--
[source,sbt]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.5.1"
----

This will automatically use the Scala 2.12 or 2.13 builds, as appropriate for your SBT project.
--

Gradle::
+
--
It can be included in your `build.gradle` like this for 2.13:

[source,groovy]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.13', version: '1.5.1'
}
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--

Maven::
+
--
It can be included in your Maven `pom.xml` like this for 2.13:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.13</artifactId>
        <version>1.5.1</version>
    </dependency>
</dependencies>
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--
====

== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically by the Capella free trial.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Here's the above Hello World example, broken down into individual actions.

First pull in all the imports we'll be using:

[source,scala]
----
include::example$Cloud.scala[tag=imports,indent=0]
----

=== Connect

Now that you have the Scala client installed, try out the following to connect to a Couchbase cluster.
The basic connection details that you'll need are given below -- for more background information, refer to the xref:howtos:managing-connections.adoc#connection-strings[Managing Connections page].

[{tabs}]
====
Couchbase Capella::
+
--
You connect to a https://docs.couchbase.com/cloud/index.html[Couchbase Capella] cluster the same as any other cluster, except that the use of TLS is mandatory, and the `couchbases://` connection string prefix should be used to allow DNS SRV lookup.

IMPORTANT: As of Scala SDK version 1.3.0, the standard certificate required to connect to a Capella cluster is automatically included with no additional configuration.

[source,scala]
----
include::example$Cloud.scala[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 1.4 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:scala-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Couchbase Server::
+
--
[source,scala]
----
include::example$StartUsing.scala[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost` as shown here.
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

NOTE: `Cluster.connect` returns a `Try[Cluster]`, as the Scala client uses functional error handling and does not throw exceptions.
You'll see examples later of how to better handle a `Try`, but for simplicity here we'll assume the operation succeeded and get the result as a `Cluster` using `.get`.



////
[TIP]
.Connecting to Cloud Native Gateway, for Kubernetes or OpenShift
====
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string -- read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
====
////


Following successful authentication, the bucket can be opened:

[source,scala]
----
include::example$Cloud.scala[tag=bucket,indent=0]
----

`waitUntilReady` is an optional call.
Opening resources such as buckets is asynchronous -- that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first Key Value (KV) operation on the bucket will wait for it to be ready.
As with `Cluster.connect`, we use `.get` on the result here for simplicity.

The Scala SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
_Collections_ allow documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.

[source,scala]
----
include::example$Cloud.scala[tag=collection,indent=0]
----

If you do not refer to a named collection, you can access the 'default collection', which includes all documents in a bucket, and is forwards and backwards compatible with all supported versions of Couchbase Server.


=== JSON

Now we can do some simple Key Value operations.  First, let's create some JSON.

The Scala SDK directly supports several popular JSON libraries, including https://github.com/lihaoyi/upickle[uPickle/uJson], https://circe.github.io/circe/[Circe], https://github.com/playframework/play-json[Play Json], https://github.com/typelevel/jawn[Jawn], and https://github.com/json4s/json4s[Json4s] (if you'd like to see your favorite supported, please let us know).
In addition you can supply JSON encoded into a `String` or `Array[Byte]`, opening the door to any JSON library; https://jsoniter.com/[Jsoniter] and https://github.com/FasterXML/jackson[Jackson] have been tested this way, but any should work.

You can also directly encode and decode Scala case classes to and from the SDK.

To make things easy and to help get you started, the Scala SDK also bundles a home-grown small JSON library, which you are free to use instead of or alongside any of the other supported JSON libraries.
The philosophy behind this library is to provide a very easy-to-use API and the fastest JSON implementation possible.

These options are described in detail xref:howtos:json.adoc[here], but to get us started let's created some simple JSON using the built-in JsonObject library:

[source,scala]
----
include::example$Cloud.scala[tag=json,indent=0]
----

=== Key-Value Operations
And now let's upsert it into Couchbase (upsert is an operation that will insert the document if it does not exist, or replace it if it does).
We need to provide a unique ID for the JSON, and we'll use a UUID here:

[source,scala]
----
include::example$Cloud.scala[tag=upsert,indent=0]
----

As mentioned above, the Scala SDK will not throw exceptions.
Instead, methods that can error - such as the `upsert` above - will return a Scala `Try` result, which can either be a `Success` containing the result, or a `Failure` containing a _Throwable_ exception.
The easiest way to handle a single operation is with pattern matching, as shown above.

Now let's get the data back (this example will look a little messy due the the nested handling of multiple `Try` results, but we'll see how to clean it up shortly):

[source,scala]
----
include::example$Cloud.scala[tag=get,indent=0]
----

Here we're fetching the value for the key `docId`, converting that value to a `JsonObjectSafe` (a simple wrapper around `JsonObject` that returns `Try` results - see xref:howtos:json.adoc#error-handling-and-jsonobjectsafe[here] for details), and then accessing the value of the *status* key as a String.

=== Better Error Handling
All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using flatMap, like this:

[source,scala]
----
include::example$Cloud.scala[tag=get-map,indent=0]
----

Alternatively, you can use a for-comprehension, like so:

[source,scala]
----
include::example$Cloud.scala[tag=get-for,indent=0]
----

Either of these methods will stop on the first failed operation.  So the final returned `Try` contains either a) `Success` and the result of the final operation, indicating that everything was successful, or b) `Failure` with the error returned by the first failing operation.

=== Overloads
You'll notice that most operations in the Scala SDK have two overloads.
One will take an Options builder, which provides all possible options that operation takes.
For instance:
[source,scala]
----
include::example$Cloud.scala[tag=replace-options,indent=0]
----
These options blocks are implemented as Scala case classes, e.g. they are immutable data objects that return a copy of themselves on each change.

The other overload is provided purely for convenience.  It takes named arguments instead of an Options object, and provides only the most commonly used options:
[source,scala]
----
include::example$Cloud.scala[tag=replace-named,indent=0]
----

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
* Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
* A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The Scala SDK includes three APIs.  
The examples above show the simple blocking API, for simplicity, but you can also perform all operations in an async style using Scala `Future`, and a reactive style using Project Reactor `SMono` and `SFlux`.
Please see xref:howtos:concurrent-async-apis.adoc[Choosing an API] for more details.

The API reference is generated for each release and the latest can be found https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/index.html[here].

Couchbase welcomes community contributions to the Scala SDK.
The SDK source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/scala-sdk/37[community forum] is a great source of help.
