= Hello World
// :page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:forum-link: https://www.couchbase.com/forums/c/scala-sdk/37
:complete-code-include: include::devguide:example$scala/Cloud.scala[]
:page-partial:

// Note to editors
// 
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/release/8.1/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-scala/tree/release/3.12/modules/devguide/examples/scala
// 
// It can be seen built at
// https://docs.couchbase.com/scala-sdk/3.12/hello-world/start-using-sdk.html


[abstract]
{description}


NOTE: From 3.9.0 on, all Couchbase JVM SDKs have an aligned version number to make it easier to users to track changes. So the {name-sdk} version jumped from 1.8.x to 3.9.x, then incremented through dotminor bumps again to the current {sdk_dot_minor}.


// intro
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro]



// upsert snippet
.Upsert with a Unique ID
[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=upsert,indent=0]
----

// intro-upsert
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro-upsert]


// TIP - DEE tutoral & Student record tutorial
// include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=other-tutorials]

TIP: This page walks you through a quick installation, and CRUD examples against the Data Service.
Elsewhere in this section you can find a fully worked-through xref:hello-world:sample-application.adoc[].


== Before You Start

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=before]


// Script the docs!
// Can any of the SDK installations be scripted?


=== Prerequisites

* The Scala SDK is tested against LTS versions of Oracle JDK and OpenJDK -- 
see the xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].
* The Couchbase {name-sdk} {sdk_dot_minor} Client supports Scala 2.12, 2.13, and 3.3 through 3.7 (inclusive).


// self-managed + Capella pre-reqs
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=prereq]



== Installation

// tag::quick-install[]
More details of the installation process are in the 
xref:project-docs:sdk-full-installation.adoc[full installation guide].
In most cases, given the above prerequisites, it's a simple matter of the following for your favorite build tool:

[tabs] 
==== 
Scala Build Tool (SBT)::
+
--
[source,sbt,subs="+attributes"]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "{sdk_current_version}"
----

This will automatically use the correct build for your Scala version.
--

Gradle::
+
--
For Scala 2.13 or Scala 3.3 through 3.7, include the following in your `build.gradle`:

[source,groovy,subs="+attributes"]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_3', version: '{sdk_current_version}'
}
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--

Maven::
+
--
For Scala 2.13 or Scala 3.3 through 3.7, include the following in your Maven `pom.xml`:

[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_3</artifactId>
        <version>{sdk_current_version}</version>
    </dependency>
</dependencies>
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--
====
// end::quick-install[]


=== IDE Plugins


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=ide]


=== Grab the Code

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=complete-code]


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=connect,indent=0]
----

Note, the client certificate for connecting to a Capella cluster is included in the SDK installation.
--

Self-Managed Couchbase Server::
+ 
-- 
[source,scala]
----
include::devguide:example$scala/StartUsing.scala[tag=connect,indent=0]
----
--

Cloud Native Gateway (CNG)::
+
--
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string --
currently only compatible with recent versions of xref:operator:ROOT:concept-cloud-native-gateway.adoc[Couchbase Autonomous Operator]:

[source,scala]
----
.connect(
  "couchbase2://10.12.14.16",
  ClusterOptions
    .create(username, password)
    .environment(env)
)
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.

--
====


The `ClusterEnvironment.builder` is covered more fully on the xref:ref:client-settings.adoc#the-environment-builder[Client Settings] page.


NOTE: `Cluster.connect` returns a `Try[Cluster]`, as the Scala client uses functional error handling and does not throw exceptions.
You'll see examples later of how to better handle a `Try`, but for simplicity here we'll assume the operation succeeded and get the result as a `Cluster` using `.get`.


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=deeper-conn]


=== Opening a Bucket

Following successful authentication, open the bucket with:

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=bucket,indent=0]
----



////
client has not yet completed bootstrapping (connecting to the cluster, getting the configuration, connecting to the nodes).
////


`waitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.
As with the earlier `Cluster.connect`, we use `.get` on the result here for simplicity.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=collection,indent=0]
----


== Create, Read, Update, Delete

Couchbase documents are organized into buckets, scopes, and collections.
https://en.wikipedia.org/wiki/CRUD[CRUD operations^] -- Create, Read, Update, Delete -- can be performed upon documents in a collection.

=== JSON

We'll create a snippet of JSON to work with, using the client's own JSON library,
but you can read about the Scala SDK's support for other JSON libraries on the
xref:howtos:json.adoc[] page.

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=json,indent=0]
----

=== Insert (Create) and Upsert

`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail,
// throwing `DocumentExistsException` --
while the `upsert` operation will succeed, replacing the content.

We need to provide a unique ID as the key, and we'll use a UUID here:

.Creating a new document
[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=upsert,indent=0]
----

=== Get (Read)

The `get` method reads a document from a collection.
// If the collection does not have a document with this ID, the `get` method also throws `DocumentNotFoundException`.

As mentioned above, the Scala SDK will not throw exceptions.
Instead, methods that can error -- such as the `upsert` above --
will return a Scala `Try` result, which can either be a `Success` containing the result, or a `Failure` containing a _Throwable_ exception.
The easiest way to handle a single operation is with pattern matching, as shown above.

Now let's get the data back (this example will look a little messy due the nested handling of multiple `Try` results, but we'll see how to clean it up shortly):

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=get,indent=0]
----

Here we're fetching the value for the key `docId`,
converting that value to a `JsonObjectSafe`
(a simple wrapper around `JsonObject` that returns `Try` results -- see
xref:howtos:json.adoc#error-handling-and-jsonobjectsafe[JsonObjectSafe] for details),
and then accessing the value of the *status* key as a String.

==== Better Error Handling

All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using `flatMap`, like this:

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=get-map,indent=0]
----

Alternatively, you can use a for-comprehension, like so:

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=get-for,indent=0]
----

Either of these methods will stop on the first failed operation.  So the final returned `Try` contains either 
a) `Success` and the result of the final operation, indicating that everything was successful, or 
b) `Failure` with the error returned by the first failing operation.

=== Replace (Update) and Overloads

You'll notice that most operations in the Scala SDK have two overloads.
One will take an Options builder, which provides all possible options that operation takes.
For instance:

.The replace method updates the value of an existing document
[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=replace-options,indent=0]
----

These options blocks are implemented as Scala case classes:
they are immutable data objects that return a copy of themselves on each change.

The other overload is provided purely for convenience.
It takes named arguments instead of an Options object, and provides only the most commonly used options:

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=replace-named,indent=0]
----

CAUTION: When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.

=== Remove (Delete)

The remove method deletes a document from a collection:

[source,scala]
----
include::devguide:example$scala/KvOperations.scala[indent=0,tag=remove]
----


== Data Modeling

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=data-model]



== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=what-next]
