= Start Using the Scala SDK
:description: Get up and running quickly, installing the Couchbase Scala SDK, and running our Hello World example.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:lang: Scala
:page-toclevels: 2
:page-pagination: next
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Scala SDK allows Scala applications to access a Couchbase cluster.

== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Scala SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
[source,scala]
----
include::example$Cloud.scala[tags=**]
----
--

Local Couchbase Server::
+
--
[source,scala]
----
include::example$StartUsing.scala[tags=**]
----
--
====

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.

== Quick Install

A more detailed guide in our xref:project-docs:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}] 
==== 
SBT::
+
--
[source,sbt]
----
libraryDependencies += "com.couchbase.client" %% "scala-client" % "1.6.2"
----

This will automatically use the Scala 2.12 or 2.13 builds, as appropriate for your SBT project.
--

Gradle::
+
--
It can be included in your `build.gradle` like this for 2.13:

[source,groovy]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'scala-client_2.13', version: '1.6.2'
}
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--

Maven::
+
--
It can be included in your Maven `pom.xml` like this for 2.13:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>scala-client_2.13</artifactId>
        <version>1.6.2</version>
    </dependency>
</dependencies>
----

For Scala 2.12, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].
--
====

== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically by the Capella free trial.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Here's the above Hello World example, broken down into individual actions.

First pull in all the imports we'll be using:

[source,scala]
----
include::example$Cloud.scala[tag=imports,indent=0]
----

=== Connect

Now that you have the Scala client installed, try out the following to connect to a Couchbase cluster.
The basic connection details that you'll need are given below -- for more background information, refer to the xref:howtos:managing-connections.adoc#connection-strings[Managing Connections page].

[{tabs}]
====
Couchbase Capella::
+
--
You connect to a https://docs.couchbase.com/cloud/index.html[Couchbase Capella] cluster the same as any other cluster, except that the use of TLS is mandatory, and the `couchbases://` connection string prefix should be used to allow DNS SRV lookup.

IMPORTANT: As of Scala SDK version 1.3.0, the standard certificate required to connect to a Capella cluster is automatically included with no additional configuration.

[source,scala]
----
include::example$Cloud.scala[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 1.4 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:scala-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Couchbase Server::
+
--
[source,scala]
----
include::example$StartUsing.scala[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost` as shown here.
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

NOTE: `Cluster.connect` returns a `Try[Cluster]`, as the Scala client uses functional error handling and does not throw exceptions.
You'll see examples later of how to better handle a `Try`, but for simplicity here we'll assume the operation succeeded and get the result as a `Cluster` using `.get`.



////
[TIP]
.Connecting to Cloud Native Gateway, for Kubernetes or OpenShift
====
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string -- read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
====
////


Following successful authentication, the bucket can be opened:

[source,scala]
----
include::example$Cloud.scala[tag=bucket,indent=0]
----

`waitUntilReady` is an optional call.
Opening resources such as buckets is asynchronous -- that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first Key Value (KV) operation on the bucket will wait for it to be ready.
As with `Cluster.connect`, we use `.get` on the result here for simplicity.

The Scala SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
_Collections_ allow documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.

[source,scala]
----
include::example$Cloud.scala[tag=collection,indent=0]
----

If you do not refer to a named collection, you can access the 'default collection', which includes all documents in a bucket, and is forwards and backwards compatible with all supported versions of Couchbase Server.


=== JSON

Now we can do some simple Key Value operations.  First, let's create some JSON.

The Scala SDK directly supports several popular JSON libraries, including https://github.com/lihaoyi/upickle[uPickle/uJson], https://circe.github.io/circe/[Circe], https://github.com/playframework/play-json[Play Json], https://github.com/typelevel/jawn[Jawn], and https://github.com/json4s/json4s[Json4s] (if you'd like to see your favorite supported, please let us know).
In addition you can supply JSON encoded into a `String` or `Array[Byte]`, opening the door to any JSON library; https://jsoniter.com/[Jsoniter] and https://github.com/FasterXML/jackson[Jackson] have been tested this way, but any should work.

You can also directly encode and decode Scala case classes to and from the SDK.

To make things easy and to help get you started, the Scala SDK also bundles a home-grown small JSON library, which you are free to use instead of or alongside any of the other supported JSON libraries.
The philosophy behind this library is to provide a very easy-to-use API and the fastest JSON implementation possible.

These options are described in detail xref:howtos:json.adoc[here], but to get us started let's created some simple JSON using the built-in JsonObject library:

[source,scala]
----
include::example$Cloud.scala[tag=json,indent=0]
----

=== Key-Value Operations
And now let's upsert it into Couchbase (upsert is an operation that will insert the document if it does not exist, or replace it if it does).
We need to provide a unique ID for the JSON, and we'll use a UUID here:

[source,scala]
----
include::example$Cloud.scala[tag=upsert,indent=0]
----

As mentioned above, the Scala SDK will not throw exceptions.
Instead, methods that can error - such as the `upsert` above - will return a Scala `Try` result, which can either be a `Success` containing the result, or a `Failure` containing a _Throwable_ exception.
The easiest way to handle a single operation is with pattern matching, as shown above.

Now let's get the data back (this example will look a little messy due the the nested handling of multiple `Try` results, but we'll see how to clean it up shortly):

[source,scala]
----
include::example$Cloud.scala[tag=get,indent=0]
----

Here we're fetching the value for the key `docId`, converting that value to a `JsonObjectSafe` (a simple wrapper around `JsonObject` that returns `Try` results - see xref:howtos:json.adoc#error-handling-and-jsonobjectsafe[here] for details), and then accessing the value of the *status* key as a String.

=== Better Error Handling
All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using flatMap, like this:

[source,scala]
----
include::example$Cloud.scala[tag=get-map,indent=0]
----

Alternatively, you can use a for-comprehension, like so:

[source,scala]
----
include::example$Cloud.scala[tag=get-for,indent=0]
----

Either of these methods will stop on the first failed operation.  So the final returned `Try` contains either a) `Success` and the result of the final operation, indicating that everything was successful, or b) `Failure` with the error returned by the first failing operation.

=== Overloads
You'll notice that most operations in the Scala SDK have two overloads.
One will take an Options builder, which provides all possible options that operation takes.
For instance:
[source,scala]
----
include::example$Cloud.scala[tag=replace-options,indent=0]
----
These options blocks are implemented as Scala case classes, e.g. they are immutable data objects that return a copy of themselves on each change.

The other overload is provided purely for convenience.  It takes named arguments instead of an Options object, and provides only the most commonly used options:
[source,scala]
----
include::example$Cloud.scala[tag=replace-named,indent=0]
----

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
* Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
* A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The Scala SDK includes three APIs.  
The examples above show the simple blocking API, for simplicity, but you can also perform all operations in an async style using Scala `Future`, and a reactive style using Project Reactor `SMono` and `SFlux`.
Please see xref:howtos:concurrent-async-apis.adoc[Choosing an API] for more details.

The API reference is generated for each release and the latest can be found https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/index.html[here].

Couchbase welcomes community contributions to the Scala SDK.
The SDK source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/scala-sdk/37[community forum] is a great source of help.
